### ISSUE TITLE
mark a container as non-infectious

### ISSUE THREAD

**Issue by aktau** [mozilla/multi-account-containers#1022]
I just installed the add-on and was trying to organize my life. Suppose I go to social site X (or search engine Y) and on that site there's a lot of links. When I click on those links, I stay in the container I created for site X, possibly leaking cookies all over the place.

I understand that maintaining a container across browsing is beneficial in some contexts, but I'd like the option to make a site non-infectious. For example: open facebook.com in the Facebook container, but when clicking on a link there, use the default (or some other) container.

NOTE: I tried to search in open issues for something like this, but failed after 3 pages. Apologies if it was already reported, I'd like to add my +1 there.

**Comment by stoically** [comment]
Opening external links from social site X or search engine Y all in the same "infectious" container might be not the best idea either, since they would share cookies in there. You might be interested in a Throw-away Container approach, available Add-ons for that purpose that I know of are [Containers on the Go](https://addons.mozilla.org/en-US/firefox/addon/containers-on-the-go/), [Click To Contain](https://addons.mozilla.org/en-US/firefox/addon/click-to-contain/) or [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) (disclaimer: I'm the author of the last one).

**Comment by groovecoder** [comment]
Sounds kinda like #847 too?

**Comment by aktau** [comment]
@groovecoder yes, I think the suggestion in #847 would solve my problem nicely. You can close this issue if you want. I think it's similar enough. Thanks!

**Comment by groovecoder** [comment]
I'm going to close this. The UX & coding involved on this are complicated enough that they're currently out-of-scope for the add-on. We can re-open if we want to later.

**Comment by ThisUserIsEpic2** [comment]
I think this is a good idea.
