### ISSUE TITLE
Ctrl+T should open a dialog for choosing container

### ISSUE THREAD

**Issue by Hoween** [mozilla/multi-account-containers#1031]
When using multi-account-containers, _Ctrl+T_ shortcut opens some "default" tab with some default context. So when I need to open tab with specific container, I need to click on toolbar button. Very anoying.

Wanted behavior is opening extensions's dialog for choosing container on _Ctrl+T_ (at least allow this possibility through configuration). Thanks.

**Comment by stoically** [comment]
With the new version there will be [a keyboard shortcut](https://github.com/mozilla/multi-account-containers/pull/992#issuecomment-346135625).

Overwriting default Ctrl+T behavior is not that easy, since the WebExtension API doesn't allow it natively. It would open the tab, close it immediately and then some other action could occur like showing the MAC Container Popup. Or maybe show a container selection instead of about:newtab in the browser window - would make for a good Add-on I guess.

**Comment by TanviHacks** [comment]
If you go to about:config and set privacy.userContext.longPressBehavior to 1, you can click the plus button and get the drop down menu where you can choose a container.

**Comment by groovecoder** [comment]
You can use the keyboard shortcut to open the dialog, or use the about:config setting to use this mouse. We won't be able to change this in the add-on, and Firefox Ctrl+T behavior likely won't be changed either.

**Comment by stoically** [comment]
For me the `privacy.userContext.longPressBehavior` setting always resets to `2` (tested with fresh profile and Firefox58 on Ubuntu16.04) after Firefox restart, even when defined in a `user.js`. Maybe any idea what causes this?

**Comment by Hoween** [comment]
Confirming stoically's problem, Firefox 58.0.2 on Windows 7.
