### ISSUE TITLE
[Feature request] Select container when clicking external link

### ISSUE THREAD

**Issue by hoshsadiq** [mozilla/multi-account-containers#1035]
It would be nice to be able to select which container to open a link in that comes from outside Firefox. E.g. if you click a link in slack, I want to open it in Work container, or if I open a link in email, I wanna decide which container to open it in.

I'm not sure if this feature has already been requested, but I had a look through the issues, and didn't find it.

**Comment by jonathanKingston** [comment]
How would you go about picking the alternative? Extensions could provide a menu on clicking the link however this would be super intrusive to be the default.

I also think this is probably very duplicated depending on what you are after.

Thanks

**Comment by hoshsadiq** [comment]
First of all, it wouldn't be the default, it would be an option to enable such a system (I can imagine the majority not wanting this).
Second, what my intention with this feature request is something similar (but likely much less feature filled) to [Choosy for OSX](https://www.choosyosx.com/) but for containers rather than browsers. This addon already has some features from Choosy (e.g. the always open in container feature). Combining these two, would make it a super handy and quick to either automatically open links in a specific container, which should catch the majority of links.

**Comment by hoshsadiq** [comment]
This would potentially eliminate the need for a "change container for tab" feature that can be risky as described in https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers

**Comment by jeckhart** [comment]
Just dropping in to "re-up" this request. There are OFTEN times that I click a link in Slack, or authenticate a native app via oauth in the browser (I'm looking at you Zoom!) where the links should be opened in a specific container but instead are opened in the default container.

The problem extends itself when those links go through a series of redirects, usually because of an auth pattern that will never work in that container. For example, when I wanted to login to Zoom, it would open the login link, which then redirects to an OAuth provider, which fails because the auth for my Zoom account doesn't live in the default container, it's sequestered to another container.

I don't know if we're able to tell when a link comes from "within" Firefox or from the outside. If you can help me with that mechanism I will happily mock up a sample pr for review.

Thank you!!!

**Comment by grahamperrin** [comment]
Implemented by **Always In Container**. Please see the screenshot at https://bugzilla.mozilla.org/show_bug.cgi?id=1692124#c1

**Comment by grahamperrin** [comment]
> from outside Firefox

▶ #706

@hoshsadiq please close this duplicate. Thank you.

**Comment by hoshsadiq** [comment]
Thanks! I didn't realise.
