### ISSUE TITLE
Always open in prompt not appearing

### ISSUE THREAD

**Issue by gibfahn** [mozilla/multi-account-containers#1058]
For some reason I'm not able to always open https://users.rust-lang.org/ in a custom container.

### Normal process

1. Open site in new `Coding` tab and check the `Always open in` box:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/15943089/34387188-69f1fafe-eb35-11e7-9b7a-328fb0c99a08.png">
2. Close tab, open new tab (`Default` container), check box, click `Always open`:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/15943089/34387219-837c659a-eb35-11e7-834b-d63556a5f322.png">

### Not working

1. Open site in new `Coding` tab and check the `Always open in` box:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/15943089/34387272-d121b7e6-eb35-11e7-870a-23e39dce8f46.png">
2. Reopen site, it doesn't show the popup:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/15943089/34387285-ebfaf62c-eb35-11e7-94dc-750367597081.png">

<img width="301" alt="image" src="https://user-images.githubusercontent.com/15943089/34387288-f3fdff04-eb35-11e7-84c0-97873e116c5e.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/15943089/34387300-025e4090-eb36-11e7-8fae-13e873aea451.png">

**Comment by TriMoon** [comment]
This is as far as i can tell intended behaviour...
The **REAL** problem is removing that decision again in a user friendly way.
Only way is to uncheck the option to "always open in" while the page is open, from the button menu of this extension...

oh wait that option does not show checked for "Default"? 🤣

**Comment by gibfahn** [comment]
>oh wait that option does not show checked for "Default"? 🤣

Yeah it's weird, and I've only seen it for this site, but if I open it in a default tab I get:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/15943089/34715504-d072c684-f524-11e7-8fd5-4b373373374f.png">

and if I open it in a `Coding` tab I get:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/15943089/34715521-dffa25ac-f524-11e7-95d6-098fb9d2d899.png">

What I expect is to get the "Would you like to always open this in `Coding`" confirmation page.

**Comment by groovecoder** [comment]
We're having trouble following the steps to reproduce this bug. Are you sure you clicked "Open in Coding Container" when you first saw the interstitial?

@SoftVision-EmilPasca - can you help us with STR on this issue?

**Comment by SoftVision-EmilPasca** [comment]
I have tested this issue on Windows 10 x64 with the latest Nightly (59.0a1-20180110100224) and latest Firefox Multi-Account Containers (5.0.1) and haven't managed to reproduce this issue.

Here's one of the scenarios I've followed when trying to reproduce the issue:

1. Edit one of the containers name to `Coding`;
2. Open a new `Coding` container tab and navigate to https://developer.mozilla.org/en-US/.
3. Check the `Always open in Coding` checkbox.
4. Open a new `Coding` container tab and navigate to https://users.rust-lang.org/
5. Check the `Always open in Coding` checkbox.
6. Opened a new default container tab and navigate to https://developer.mozilla.org/en-US/ 
7. Check the `Remember my decision for this site` checkbox and click on the "Open in Coding Container" button.
8. Open the Containers panel and observe the `Always open in Coding` checkbox.
9. Opened a new default container tab and navigate to https://users.rust-lang.org/
10.  Without checking the `Remember my decision for this site`, click on the "Open in Coding Container" button.
11. Open the Containers panel and observe the `Always open in Coding` checkbox.


When verifying in both steps (8 and 11) the `Always open in Coding` checkbox was correctly checked.

@gibfahn , can you please add more details regarding your environment, such as operating system, Firefox version and installed addons?

Also could you please provide a screen recording of the issue or more explicit steps in order to help us reproduce the issue on our end?
*Note that GitHub doesn't allow video attachments, so if you do manage to record the issue I would suggest that you upload the recording on Google drive or other cloud service and post the link to it.

Thank you!

**Comment by gibfahn** [comment]
Okay, I ended up resetting my containers and this no longer happens, so I'll close this out.
