### ISSUE TITLE
Support AZERTY-based keyboard layouts for shortcuts

### ISSUE THREAD

**Issue by ghostofkendo** [mozilla/multi-account-containers#1081]
As of version 5.0.1, the shortcut to open the addon's popup menu is `Ctrl+.`.

If one tries to type this shortcut using an AZERTY-based keyboard layout, the addon does not recognize the shortcut because this layout requires one to hold Shift to produce the `.` character, see https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg
Therefore, users of this type of layout can type `Ctrl+Shift+.` but not `Ctrl+.`.

What would be a good way for the addon to support AZERTY-based keyboard layouts?

**Comment by jonathanKingston** [comment]
Currently Firefox doesn't permit changing these for layout, user preference etc.
I'm fairly certain the Firefox team is working on this as people have their own preferences anyway.
I'm thought we had a dupe for this, I can't find it though.

**Comment by ecololo** [comment]
Hi,
Is there a way to use this add-on on an azerty keyboard ? I don't find how to do it and if it's impossible I think it must be considered as a bug.
Regards

**Comment by maxpv** [comment]
Hi,
Someone has an update on this bug, or managed to overpass it through an extension ?
Thanks.

**Comment by trollepierre** [comment]
Hi, same issue one year later. No update?

**Comment by stoically** [comment]
Starting with Firefox 66 it's possible to reassign keyboard shortcuts on the Add-on overview page.

**Comment by dnahol** [comment]
I'd like to work on this issue. Can you assign it to me please? @groovecoder @maxxcrawford 

I want to add an additional shortcut for this that will be accessible to an AZERTY keyboard. I was thinking either: 
Ctrl+Shift+. 
as suggested above 
or 
Ctrl+; 
since the AZERTY link above shows that . = Shift+;

**Comment by stoically** [comment]
Personally I'd say we close this one and refer to the possibility to change the shortcuts in the Firefox preferences (since version 66), as otherwise we'd end up providing shortcuts for all kinds of keyboard layouts.

**Comment by alex-devg** [comment]
I have Firefox 73.0.1 64Bits and Firefox Containers Version 6.2.1
But I don't find any shortcuts parameters to edit ? Am I missing something somewhere ?

**Comment by dannycolin** [comment]
> Personally I'd say we close this one and refer to the possibility to change the shortcuts in the Firefox preferences (since version 66), as otherwise we'd end up providing shortcuts for all kinds of keyboard layouts.

I agree with @stoically. We currently can't support multiple keyboard layout in a sane way and there's for quite some time now a way to modify the default (See: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox). 

I'll close this issue and invite folks to follow https://bugzilla.mozilla.org/show_bug.cgi?id=1418984 since
