### ISSUE TITLE
disable and re enable

### ISSUE THREAD

**Issue by kerenbir** [mozilla/multi-account-containers#1082]
this really make me shock i just disable this add onn and re enable again and **** i lost all my container just like new.

**Comment by SoftVision-EmilPasca** [comment]
Hy @kerenbir, Thanks for reporting this issue.
Could you please provide more information regarding your environment such as operating system, Firefox version and addons that you have installed? Any other information that you think it may be relevant to this issue could help us investigate this further.

**Comment by kerenbir** [comment]
im using windows 10 and firefox version 57.0.4 add ons firefox multi accounts container. i have do nothing im just disable this addons and so enable again and yeah lost i lost all my container.
hope you fix this asap becouse this really make me shock

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce the issue on Windows 10 x64, Mac 10.13 and also on Arch Linux (4.12) x64 with the latest Firefox Release(57.0.4) and the latest Firefox Multi-Account Containers (5.0.1).

The issue is not reproducible when testing it with the latest Nightly (59.0a1-20170915220136).

[Additional Notes]:
- Attached a screen recording of the issue: 
![containers_enable_disable_issue](https://user-images.githubusercontent.com/20083658/34982827-4a95ec68-fab4-11e7-9255-b789b6d9613c.gif)

**Comment by kerenbir** [comment]
yeah the question is where is container #1 you just make?

**Comment by kerenbir** [comment]
container #01

**Comment by kerenbir** [comment]
yeah i hope fix this

**Comment by groovecoder** [comment]
This may have been by design. (@jonathanKingston?)

IIRC when the add-on is disabled or un-installed, we destroy any data that the add-on created.

Is there already a bug to only destroy the data during *uninstall* - i.e., don't destroy data during *disable* ?

**Comment by groovecoder** [comment]
Sorry, this is by design. We need to delete container data when the add-on is disabled, in case the user goes on to un-install the add-on completely.
