### ISSUE TITLE
Adding number to container name opens a tab

### ISSUE THREAD

**Issue by c0deschnitzel** [mozilla/multi-account-containers#1084]
How to:
1. Add a new container or edit an existing one
2. Add a number -> enjoy

Addendum:
If you add "1" to the name it opens a new tab of the first container and so on. If you add a number of a non-existing tab it just closes the edit mode or goes back to start (= edit window).

Is this expected behavior? If yes, it's not intuitive ^^

edit: Tested with 57.0.4 (64-bit) on Win 10 1709

**Comment by gene1wood** [comment]
Here's a screen recording video of this bug in action

[![Alt text](https://img.youtube.com/vi/T4mQa3Jg4Do/0.jpg)](https://www.youtube.com/watch?v=T4mQa3Jg4Do)

**Comment by gene1wood** [comment]
This bug happens not only for container names with numbers in them but also container names with any special characters that have to be typed with <kbd>Shift</kbd>-<kbd>0-9</kbd> like `!` or `@` which means this must be a regression as all my existing container names have the `@` sign in them (email addresses)

**Comment by TanviHacks** [comment]
We recently took a keyboard shortcut patch.  Looks like that is applying to all screens instead of just the first screen.  Thanks for catching this and filing the bug!

**Comment by groovecoder** [comment]
@crenwick - could you take this on?

**Comment by crenwick** [comment]
Haha, yeah that makes sense. I can take a look at fixing it this week.

**Comment by mozjag** [comment]
Ran into this on Mac as well on Nightly 60.0a1 (2018-01-24).

1) As a work-around, if you use Firefox's built-in support (hold the tab-+ button, click "Manage containers") you can add/edit with numbers and their shift-keyed characters.

2) Since you mentioned it, I tried to get the keyboard shortcuts working on the first screen (the one opened from the add-on's button, right?), but no luck. They do work once I'm in the "Edit Containers" screen. Might wanna check that out while you're in there.

**Comment by crenwick** [comment]
PR for fix: https://github.com/mozilla/multi-account-containers/pull/1097

Another temp work around (for people that see this before the fix is published) is to copy-and-paste your desired container name from another text box.
