### ISSUE TITLE
When a container is hidden, "move tabs to new window" opens two of every tab in said container

### ISSUE THREAD

**Issue by wpcsoftcharles** [mozilla/multi-account-containers#1109]
if i have 5 tabs in a container that's currently hidden, and i want to re-open that container in a new window, the "move tabs to new window" option in that container currently opens a new window with 10 tabs in

**Comment by falolaf** [comment]
You could give my fork of the m.a.c. a try:
https://github.com/falolaf/multi-account-containers/tree/my_fixes_on_5_0_1

You have to load it through about:debugging though. Select any file in the src folder.

This is the fix I have added which prevents showing duplicate tabs:
https://github.com/falolaf/multi-account-containers/commit/289e1226b9740da600da772abeafe2e73b6de673

The aim with the fix was though to prevent all hidden tabs to be shown when a new tab is opened in the same container. As a side effect the duplicate tab problem also vanished.

**Comment by groovecoder** [comment]
@falolaf - any reason you haven't submitted that fix in a PR? Does it conflict with something in master?

**Comment by wpcsoftcharles** [comment]
Great, that works perfectly, thanks @falolaf 

Just to be sure, should I close this issue now or leave it open till it's implemented in the master, seeing as it's still an issue there?

**Comment by falolaf** [comment]
@groovecoder Well, as the fix of the two tabs issue was only a side effect of the fix for not showing all hidden tabs I believe that it is not that easy to just apply this fix to master. I also believe that showing all hidden tabs in a container is the prefered behaviour in master so applying this fix will take that away. For me that would be desired behaviour though. Not showing all hidden tabs that is. I loathe that 20 hidden tabs are opened just because a new tab in the same container is opened. Especially as moz-extension urls are not saved or loaded by m.a.c. addon. At least not on master. I have a fix for that too in the same branch as I mentioned above.

**Comment by falolaf** [comment]
@wpcsoftcharles I don't think this issue should be closed as the fix is not in master and I don't know of a proper solution only for the two tabs issue. As I mentioned the fix is only a side effect.

**Comment by wpcsoftcharles** [comment]
@falolaf Ok, that's what I thought.

How can I add permanent extensions? ATM I'll have to add it via about:debugging every time Firefox starts up

**Comment by wpcsoftcharles** [comment]
@falolaf Ok, that's what I thought. How do I add this extension permanently? ATM I will have to add it every time I restart my browser

**Comment by falolaf** [comment]
@wpcsoftcharles Sorry for late response...
For the moment I would say it is only possible to add via about:debugging as I believe it needs to be signed otherwise and I have not bothered to do that process.
