### ISSUE TITLE
New multi-account-container tab hangs for several seconds

### ISSUE THREAD

**Issue by ecotechie** [mozilla/multi-account-containers#1110]
Name 	|Firefox
-- | --
Version 	|59.0b5
Build ID 	|20180128191456
Update |History 	
Update Channel 	|aurora
User Agent 	|Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
OS 	|Linux 4.13.0-32-generic
Multiprocess Windows 	|1/1 (Enabled by default)
Web Content Processes 	|4/4
Stylo 	|content = true (enabled by default), chrome = false (disabled by default)
Google Key 	|Found
Mozilla Location Service Key 	|Found
Safe Mode 	|false

Whenever I open a new, blank, Multi Account Container Firefox hangs for about 5 seconds. This is using the button on the taskbar or from the file menu. If I open a link in new container tab it opens fine and if I open a new regular tab it also opens fine...

Thanks

**Comment by groovecoder** [comment]
@SoftVision-EmilPasca - can you reproduce this?

@ecotechie - can you provide a list of other addons you have installed?

**Comment by SoftVision-EmilPasca** [comment]
I have tested this issue on Ubuntu 16.04 x64 with the latest Firefox release (58.0.2), Firefox(59.0b5), Firefox(59.0b14) and the latest Nightly (60.0a1-20180304220118) with Firefox Multi-Account Containers (6.0.0) and haven't managed to reproduce this.

Whenever opening a new blank tab, it is opened instantaneously.

@ecotechie, could you please provide a list of the addons that you have installed as sugested by @groovecoder?
Also could you check if the issue is reproducible on the latest Firefox Release and Nightly build?

**Comment by ecotechie** [comment]
Sorry to take so long to reply :blush: 
Since updating, I've had no more problems...
Running 60.0b14 (64-bit) now.

Thanks for the response! Using container tabs ALL day long :grinning:
