### ISSUE TITLE
Multiple Firefox identities too?

### ISSUE THREAD

**Issue by dripfeed** [mozilla/multi-account-containers#1136]
I have two Google Chrome identities (work and personal). When I log into each of them in Chrome I get a browser with different bookmarks toolbars. So, I have my personal bookmarks on one Chrome window and my work bookmarks in a separate Chrome window, along with separate cookies, cache, etc. etc. 

Can this Firefox multi-account container be extended to offer the same functionality? I really don't want my work and personal web activities smooshed together.

**Comment by stoically** [comment]
Separating [bookmarks](https://bugzilla.mozilla.org/show_bug.cgi?id=1213290) and [history](https://bugzilla.mozilla.org/show_bug.cgi?id=1283320) is planned too, but [not yet available](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers).

Duplicates: #47 and #323, please vote there

**Comment by dripfeed** [comment]
Thanks.

**Comment by groovecoder** [comment]
Closing as dupe.

**Comment by pcowgill** [comment]
This issue is mainly about having different bookmarks for each container, which is a bit different from having a different history (https://github.com/mozilla/multi-account-containers/issues/47) and being able to open one bookmark into a specific container (https://github.com/mozilla/multi-account-containers/issues/323)
