### ISSUE TITLE
browser.storage.local vs browser.storage.sync

### ISSUE THREAD

**Issue by GregBrimble** [mozilla/multi-account-containers#1149]
Hi all,

Just wondered why the decision was made to use `browser.storage.local` for assignments, rather than `browser.storage.sync`, and if the latter would ever be considered. This would allow for "Always open in" container preferences to be synced across devices.

https://github.com/mozilla/multi-account-containers/blob/master/src/js/background/assignManager.js#L9

Thanks!

**Comment by stoically** [comment]
Just replacing `local` with `sync` wouldn't do it, because assignments are container-id-specific and those are in turn Firefox-profile-specific. Also Sync comes with a variety of challenges to do right, like who wins in case of conflict and stuff like that.

Also, here's duplicate that you could vote https://github.com/mozilla/multi-account-containers/issues/339
