### ISSUE TITLE
How open 50 containers in one shot?

### ISSUE THREAD

**Issue by lucaspinelli94** [mozilla/multi-account-containers#1251]
It's all ok, this plugin is amazing but how can i open 50 containers in one shot?

I mean, if i've a bookmark folder with 50 pages, i press the roller to open all 50 pages in one shot
But how can i do the same with 50 containers for example? Open 1 by 1 is not a good solution.

**Comment by lucaspinelli94** [comment]
No ideas guys? Is very boring waste time to open 50 or 100 containers manually.

I wanna open it like a bookmarks in one folder.

**Comment by groovecoder** [comment]
If the bookmarks are assigned to specific containers, they could automatically open into their specific containers.

There's also https://github.com/mozilla/multi-account-containers/issues/323 which depends on platform-level bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1334696

**Comment by kendallcorner** [comment]
Yes, please vote (:+1:) or discuss on #323 to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Comment by MichaelTunnell** [comment]
@dannycolin 
I am in no way attempting to build hostility, I am pointing out why the reasoning for migration is frustrating because that was the sole basis for why we wanted to have this thread separate for almost 6 years now. #323 comment about this was an afterthought of the original right click context menu request that was completed years prior while this thread sat in obscurity because of the repeated closures and burying inside a seemingly completed feature request.

I hope my belief of losing comments would be wrong but based on that thread not linking to these for context and being posted 8-9 months ago and was replacing these without links for relevance. I think it is reasonable to have that belief after 6 years of frustrations related to what is now deemed as not a duplicate since it has a specific thread on this new platform.

Another frustrating thing is that you are locking threads as if your interpretation is the only one that has validity. I wouldn't have been as frustrated by the migration without the locking of #323 and now I have to comment here because of the locking of #854 because you interpreted my comment as hostility when it was in fact not hostile at all it was a pointing out why so many are frustrated as we have been saying the visibility argument for this entire time.
