### ISSUE TITLE
provide downloadable installer

### ISSUE THREAD

**Issue by aplatypus** [mozilla/multi-account-containers#1398]
Mozilla have crippled Firefox such that I may not download this plugin, let alone install it.

Please provide an official binary download for the plugin via this GitHub project.

![image](https://user-images.githubusercontent.com/67028/57186059-d4699480-6f1b-11e9-8114-d52a366c3dde.png)

This is really not how I need to spend my one day off (Sunday at that)

**Comment by groovecoder** [comment]
This was caused by a larger issue with all add-ons, described here:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

A release was made yesterday to fix the download + install issue:

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

To address the underlying issue of data loss when container add-ons are disabled or un-installed, we have both a long-standing GitHub issue in this repo:

https://github.com/mozilla/multi-account-containers/issues/1236

And a corresponding bug in bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

Please upvote and/or comment there so we can consolidate all the work in this area.
