### ISSUE TITLE
Lost all customizations

### ISSUE THREAD

**Issue by dry4ng** [mozilla/multi-account-containers#1399]
The recent [addon issue](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) resulted in completely reset state of multi-account-containers. I have lost all customizations and tab specific cookies.

**Comment by TrekkieTechie** [comment]
I have also had my MAC configuration reset to defaults, and it's going to be a pretty frustrating exercise to reconfigure it on each of my computers.

Can the configuration not be stored somewhere that it won't be erased if the extension is disabled? If that isn't possible, could we have the ability to export and import our configuration? (Honestly, that would be a great feature regardless.)

**Comment by JackStamper** [comment]
I had a Container with all my "Bookmarks", meaning Articles, Videos, or even Pages on Multi-Page stories I was at. Loosing them is frustrating, as recovering them all is probably impossible.

Is there any guarantee this won't happen again?

**Comment by cody42** [comment]
My configuration has been restored, but on my wifes pc all configurations are lost. No obvious differences in the settings regarding addons, we both have settings and addons synced using a firefox account. Seems pretty random to me.

Export/import of the configuration would truly be a great feature.

**Comment by JackStamper** [comment]
I just resigned to make new Customizations...and the first new category I opened, was filled with the Tabs from the first category I lost. Every new category was then filled with the tabs of the next lost category. They...were all there. I just needed to make enough new categories to capture them.

**Comment by mwillers** [comment]
For me, all data was lost as well ...
Dear devs, please instruct on how to recover the data.
Thanks

**Comment by jonlm** [comment]
Sigh. This happened to me too. There is now an official note saying that they were irrevocably lost:

https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox#w_container-add-ons

That links to a bugzilla which will attempt to prevent this from happening again in the future. If you read that bug you'll see that the containers were actively deleted due to some javascript that ran.

Your only chance to restore them is via a disk backup of your Firefox profile. Personally, I'm not going to bother with that. Too much of a pain to deal with.

**Comment by groovecoder** [comment]
This was caused by a larger issue with all add-ons, described here:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

A release was made yesterday to fix the download + install issue:

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

To address the underlying issue of data loss when container add-ons are disabled or un-installed, we have both a long-standing GitHub issue in this repo:

https://github.com/mozilla/multi-account-containers/issues/1236

And a corresponding bug in bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

Please upvote and/or comment there so we can consolidate all the work in this area.
