### ISSUE TITLE
I cannot even Download it.  Why?  

### ISSUE THREAD

**Issue by Brass2387** [mozilla/multi-account-containers#1401]
When I click "Add to Firefox", it says "Download failed. Please check your connection."  
I am obviously online...  my internet connection is good.  FF version 66.  Any clues?
Thanks.

**Comment by rdelval** [comment]
There's an issue with a certificate that expired. No new extensions can be installed at the moment. Long story short, wait until Mozilla pushes an update or enable studies. See here for more details here https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by Brass2387** [comment]
Well, THAT explains it, Rdelval.  Thanks for that information.
I DID have a different "containers" thing installed...  I think the name was Paranorma, or something like that.  It just all-of-a-sudden Disappeared!  I then had all 417 of my tabs on Only One browser/container, instead of the 30? that they were in.  Did this Certificate problem cause that extension to fail?

**Comment by rdelval** [comment]
Yes, all extensions are disabled unless you take steps to allow Firefox to re-enable them as outlined in that blog post from Mozilla.

**Comment by groovecoder** [comment]
This was caused by a larger issue with all add-ons, described here:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

A release was made yesterday to fix the download + install issue:

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

To address the underlying issue of data loss when container add-ons are disabled or un-installed, we have both a long-standing GitHub issue in this repo:

https://github.com/mozilla/multi-account-containers/issues/1236

And a corresponding bug in bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

Please upvote and/or comment there so we can consolidate all the work in this area.
