### ISSUE TITLE
All containers are gone after Firefox certificate shenanigans.

### ISSUE THREAD

**Issue by garretwilson** [mozilla/multi-account-containers#1405]
I'm on Windows 10 with Firefox 66.0.4. I have been using multi-account containers for months. The version I currently have appears to be 6.1.0, last updated January 25, 2019. I had removed all default containers and added a single custom container.

As you know Firefox recently accidentally [disabled all extensions](https://discourse.mozilla.org/t/fixed-certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047). At this point I was on a previous 66.0.x version of Firefox.

They pushed out a [temporary fix](https://discourse.mozilla.org/t/fixed-certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/14), and then yesterday they updated to Firefox 66.0.4, which I have now.

Last night when I hit `Ctrl+.` to go to my container, my custom container was gone and now I only see the default "Personal", "Work", "Bank", and "Shopping".

**Comment by groovecoder** [comment]
Sorry. You're correct this was caused by a larger issue with all add-ons, described here:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

A release was made yesterday to fix the download + install issue:

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

To address the underlying issue of data loss when container add-ons are disabled or un-installed, we have both a long-standing GitHub issue in this repo:

#1236

And a corresponding bug in bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

Please upvote and/or comment there so we can consolidate all the work in this area.
