### ISSUE TITLE
Feature Request: automatically open in new default tab if site isn't "saved" in any container.

### ISSUE THREAD

**Issue by NessunoIM** [mozilla/multi-account-containers#1419]
Can you add the possibility to open directly on new default tab when I click inside a link in specific container, if the site link that i clicked is not saved as "open in specific tab".
This actually is possible only with Facebook container.

**Comment by Dormann** [comment]
I also would greatly appreciate this feature.
As I use google (:-S) to search something, I would like for any link in the search result page to be opened automatically outside the container, even if the target site is not associated to any specific container.
With this in mind, the url would need to be cleaned in order to get rid of any data related to google.

**Comment by lhorace** [comment]
Duplicate https://github.com/mozilla/multi-account-containers/issues/914.

It might be a good idea to move the discussion there since that issue has votes and additional context.

Cheers.

**Comment by kendallcorner** [comment]
I'm closing since this is a duplicate. As lhorace said, please send +1s and discussion to #914 . Thanks!
