### ISSUE TITLE
Automatic site-specific containers

### ISSUE THREAD

**Issue by joshhansen** [mozilla/multi-account-containers#1421]
This is a feature request asking for a configuration option (likely off by default) that enables opening sites in per-site containers by default, unless otherwise assigned to a different container.

For example, if I visit github.com, by default my current configuration opens it in the default container. However, I would prefer that by default any site I open be separated from all other sites unless there is good reason for them to share cookies, etc.

With this feature enabled, the behavior would be that github.com would open in a hidden/implicit "github.com" container rather than the default container. This could also be framed as simply divvying up the default container into site-specific pieces, so "Default: github.com", "Default: amazon.com", etc.

It may be desirable to list these automatically created containers separately from those created manually, or to distinguish them visually (lack of a star icon, something like that.) Presumably extensions like Cookie AutoDelete would allow automatic deletion of automatic site-specific containers, in which case the behavior of tabs within those containers reduces to something very similar to a private browsing tab.

This is a fairly aggressive option but most websites appear to function well in isolation from each other as attested by visiting a site in private browsing mode. To isolate all sites by default would sever many of the popular modes of tracking, but in a manner indistinguishable from being opened on a new web browser.

A corollary feature would be to allow the joining or merger of containers should inter-site communication be deemed necessary.

**Comment by arnout** [comment]
For the "joining", you can always reopen a tab in a new container, and afterwards you can set the "Always open in ..." option to persist it. So that feature is not strictly needed.

It would be useful instead to have a right-click option to open a URL in the same container (when the default is to open it into a new site-specific container). The latter would actually be useful in general: I have a github-specific container, but sometimes I may want to open a link to a github URL in the current container (because I *don't* want to be logged in into github when opening that link).

**Comment by michaeljfriedman** [comment]
I fully support the implementation of this feature, though we should also be aware that this can create a very frustrating experience and should be carefully designed. For instance, sites like eBay and PayPal which are very closely integrated and rely on sharing cookies to process payments would be broken if completely isolated (at least, without user intervention). Someone technical who understands what's going on might have the intuition to right-click to open a link in the same container (if this feature is implemented) or just reopen tabs in the right containers to prevent issues like this. But it may not be obvious if the containerization is obscured as proposed here. For cases like this, it might be worth warning users (at least the first few times) when they click a link to leave a site that the new site will be opened in a new container, and if they depend on storage from the original site (like a login), they can confirm whether they want to open the link in the new container or not.

Regardless of these nuances, I would definitely want this feature, as it would do a lot to combat tracking in a way that doesn't really require much effort or have many consequences for the user experience.

**Comment by lee-b** [comment]
I agree that this would be great.  In fact, I think it's how multi-account containers should have been designed as a default workflow.

It is true that such a workflow breaks SSO on some sites: goodreads will use amazon domains during login auth, for example, and gmail.com will use google.com domains.  In this case, it's probably best to group those domains by default: there's no point isolating goodreads and amazon.com in the browser, when they share a backend auth and backend (amazon-owned) databases, and so any in-browser isolation of those two companies is only providing a false sense of security, if you're linking them through your real identity (or even email address) and the sites' parent company.  For that, some sort of adblock-like list management would probably be required.  It could be as simple as [company root] [[company child 1] [...company child N]]:

google.com gmail.com
amazon.com goodreads.com
microsoft.com hotmail.com office365.com azure.com

A related concern, solved by the same sort of lists, is that multiple user accounts will require knowledge of these underlying sites and their connections too, in order to fully isolate multiple logins.  For example, if I open azure and type in my work email, I need to also be able to open hotmail and type in a personal email, with proper isolation of the authentication.

The lists would need to be public and open to contributions, much like adblock lists.

**Comment by lee-b** [comment]
For everyone interested in this ticket, it turns out that the **First Party Isolation** add-on already works this way: https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/

Not sure of how it interacts with multi-account containers.  It would definitely be nice if multi-account worked with it, so you can log into AWS with both work and personal accounts, for example.

**Comment by grahamperrin** [comment]
@joshhansen please, do the features of recent releases of Firefox meet your requirements?

**Comment by joshhansen** [comment]
I haven't tested it but by the description it appears that Enhanced Tracking Protection in strict mode effectively implements this request. Thanks for looking into it.
