### ISSUE TITLE
website and container association being asked repeatedly.

### ISSUE THREAD

**Issue by vsrawat** [mozilla/multi-account-containers#1457]
When I defined a container and set the sites that are to open in that, I open the add-on's setting in tool bar, click on "always open in default container".

however on next session, when I click on a website, I am first presented with a tab asking "always open in default container". Why am I asked that again when I had already clicked on that in your settings.

**Comment by kendallcorner** [comment]
It sounds like what you are experiencing is expected behavior. 

The first time a site is opened after it is assigned to a container ("always open in this container"), the user is sent to the "Open this site in your assigned container?" screen, so it's clear to the user what is happening.  If you check the box to remember your choice, it shouldn't pop up again.
