### ISSUE TITLE
[Feature request] default containers, grouping containers

### ISSUE THREAD

**Issue by alsoeric** [mozilla/multi-account-containers#1477]
Two features that might be useful. The first is designating a named container as the default container. 
The second feature is organizing containers to a window. Any time you open a container, that tab is moved to the window containing tabs of the same container.

**Comment by minmazeb** [comment]
I endorse both of these suggestions.

While it is easy enough to open a tab in the appropriate container prior to visiting a page under normal browsing circumstances, the need for a user-definable default container is apparent when I click on a link in a non-browser application, which then triggers the OS to send the url to my default browser (firefox) for processing. Firefox opens such links in a non-contained context, which is not what I desire.

The second suggestion above could be tricky to design, my first approach were I to attempt an implementation (sadly, unlikely to occur) would be a little different than @alsoeric wrote. Instead of moving container tabs automatically to existing windows that already possess tabs associated with that container, I would simply add an option to prohibit any single window from hosting tabs from multiple different containers. If a tab were otherwise to be created in a window, but the new tab's container isn't the same as all of the existing tabs in that window, a new window would be created to host the new tab. In other words, if it's too difficult or time consuming to select the appropriate window to add the tab to (I can think of a few edge cases that would be problematic) it's sufficient in my opinion to at least NOT add it to an inappropriate one.

**Comment by kendallcorner** [comment]
Thanks for the input. These suggestions look like #356 and #319.  Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think these are different issues.
