### ISSUE TITLE
Shortcut does not open panel from Gmail

### ISSUE THREAD

**Issue by joebalancio** [mozilla/multi-account-containers#1483]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: MacOS 10.14.4
- Firefox Version: 68.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

Hitting the shortcut `ctrl + .` while in a tab containing `gmail.com` does not open the containers panel

### Expected behavior

Expected the shortcut to open the containers panel. In general I expect the shortcut to take precedence and work globally across all sites.

### Steps to reproduce
1. Navigate to gmail.com and log into an account
2. Type `ctrl + .`
3. Verify that the containers panel does not open

**Comment by danielsdeboer** [comment]
Seconding this. It takes a hard refresh to get it working again.

**Comment by mikejarema** [comment]
I'm on Windows 10 in Firefox 85.0b8 (64-bit, "Developer Edition").

Gmail blocking the standard shortcut was the bane of my browsing existence until I accidentally hit `ctrl + shift + .` and the new container drop-down opened. I don't believe I setup a custom shortcut, but I'm not 100% sure.

I haven't tried this alternate shortcut on Mac OS yet, but will update here if I do and it works.

**Comment by dannycolin** [comment]
This happens because Gmail is *stealing* the keyboard shortcut. You have two options to fix this issue.

1. Disable Gmail ability to override the browser shortcuts. See https://support.mozilla.org/en-US/kb/firefox-page-info-window especially the section about [Permissions](https://support.mozilla.org/en-US/kb/firefox-page-info-window#w_permissions) and [Override Keyboard Shortcuts](https://support.mozilla.org/en-US/kb/firefox-page-info-window#w_override-keyboard-shortcuts)
2. You can change the default shortcut to something else like `ctrl + shift + .`. See https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

Closing for now.
