### ISSUE TITLE
Feature Request: Integration with Firefox by Default

### ISSUE THREAD

**Issue by dabockster** [mozilla/multi-account-containers#1484]
Considering that cross site interaction (tracking or otherwise) is here to stay for the foreseeable future, and that major attempts to stop it are getting blocked (eg New York Times going around Chrome's Incognito fix), I think that this extension should be integrated as an out of the box feature in Firefox. It would give all Firefox users this functionality as opposed to the word of mouth usage it currently has, as well as serving as a benchmark for online privacy.

Thoughts on this?

**Comment by HURSSGH** [comment]
Agree. Definitely should be a FF default!

**Comment by maverick74** [comment]
I also agree with this.
IMO it should work like the Chromium Tab Groups feature... Having Containers listed in the tab bar is something intuitive (specially being able to collapse them)

**Comment by dannycolin** [comment]
Containers are already builtin Firefox by default. They only are disabled in the regular edition if you don't have an addon using it. 

If there's a specific feature you'd like to see added in the builtin version, please file a bug report directly on bugzilla.mozilla.org.

**Comment by maverick74** [comment]
I don't believe we were talking about "Containers" (which i think everyone knows that comes in firefox), but about the "**multi-account-containers**" addon that would be good to come with Firefox by default (instead of having to install it manually)... 

i believe this was what was being asked for...

**Comment by dannycolin** [comment]
@maverick74 It would have still be closed as wontfix since we can make this decision on our side.

Also, I've been collaborating with Mozilla developers for a while now and proposing specific features to be implemented upstream has more chances to be approved than asking to bundle the whole addon as is. The latter is most likely going to be closed as wontfix.

**Comment by maverick74** [comment]
OK, i just wasn't sure you got the intention of the request, hence my comment :)
