### ISSUE TITLE
"Clear all history": does it apply to the current container only UI/UX

### ISSUE THREAD

**Issue by josephernest** [mozilla/multi-account-containers#1614]
When doing CTRL+SHIFT+DEL in any container, or in a normal page (not in a container), it's not clear if the *"Clear all history"* action is going to happen:

* only in the currently selected container
* or for all Firefox

How can we improve the UI/UX to make it clearer for the user?

**Comment by bilbravo** [comment]
Which is it actually going to do? I don't know the answer.

I think if possible the dialog should tell the user which it is going to do. If necessary, make it a control in the container extension customization dialog.

**Comment by groovecoder** [comment]
I haven't tested it, but I'm 99% sure it will be "for all Firefox", because [history is still not isolated by `userContextId`](https://bugzilla.mozilla.org/show_bug.cgi?id=1283320).

There's an [upstream bug to clear history by container](https://bugzilla.mozilla.org/show_bug.cgi?id=1199470), and we would need that to happen first.

Can you show a screenshot of the UI you're looking at when you see this? I suspect this is a bug that needs to be fixed in platform.

**Comment by josephernest** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/6168083/72620188-18cc8180-393f-11ea-8148-337acaf1ebe6.png)

**Comment by groovecoder** [comment]
Okay yes, this should be filed as a bugzilla bug under https://bugzilla.mozilla.org/show_bug.cgi?id=1283320. We can't affect that UI from the extension.

**Comment by josephernest** [comment]
Is there another temporary way to "clean the whole history + cookies" for a given container, but don't touch the other containers?
