### ISSUE TITLE
Facebook appears to be tracking activity across containers

### ISSUE THREAD

**Issue by benrhughes** [mozilla/multi-account-containers#1638]
- Multi-Account Containers Version: 6.2
- Operating System + Version: Windows 10
- Firefox Version: 72.02
- also installed: Temporary Containers 1.7, VimVixen 0.26

### Actual behavior
It seems that Facebook is (somehow) tracking visited sites across container tabs. This has happened several times:
- have Facebook open in a container tab
- navigate to a site in a new temporary container tab
- Facebook starts displaying ads for the visited site within a very short period (less than 5 minutes)

At first I put it down to coincidence, but it's happening too often.

### Notes
In the container tab, I have gone to facebook.com and it prompts me to log in, so this is not a case of accidentally being logged in in the wrong container

**Comment by domohawk** [comment]
If you are not using a VPN, I think it's documented many sites latch sessions by IP address.

Also I read earlier that current firefox api does not allow compartmentalizing LocalStorage, so all containers share the same LocalStorage. Sites that store "cookies" in LocalStorage would then bypass containers.

**Comment by stoically** [comment]
Yeah, containers can only separate storage on the client-side and with that reduce tracking to some extent, it doesn't prevent the server-side to apply more sophisticated tracking mechanisms than relying on storage: like fingerprinting your browser - or, as @domohawk mentioned, simply tracking you by IP.

Best bet in this case: Trying to avoid that requests ever reach the server-side, by employing mechanisms yourself, like uBlock and pihole, or more sophisticated things like uMatrix. Oh - and the Facebook Container Add-on blocks all (sub)requests to known facebook domain outside of the facebook container by default, so that might be something for what's described in this issue.

**Comment by kendallcorner** [comment]
Yes, the two previous comments are both correct. I definitely recommend Facebook Container on top of Multi-Account Containers. I'm going to close this since it is not solvable by our addon. Thanks!
