### ISSUE TITLE
Feature Request - Organize Tabs in Dropdown

### ISSUE THREAD

**Issue by erpost** [mozilla/multi-account-containers#1639]
When you create a new container, it is appended to the bottom of the drop-down list.  There seems to be no way to then organize or sort the drop-down list.  Ideally, the functionality would be added to the "Edit Containers" action and allow drag/drop so the list could be sorted at that point.

**Comment by TuxyKey** [comment]
i would love to see the drop down menu extend it self in length. meaning if you add more containers the length of the drop-down menu increases. I understand and appreciate the scrollbar that appears but because it appearers quickly i often forget i have a container for that use. 
added benefit.. if i want to park cookies in a certain container that i don't trust i can quickly see my options..
it's just a nice to have .. really appreciate all the amazing work the developers do.
in my humble opinion this is the number add-on that dedifferentiates Firefox from other browsers.
together with cookie quick manager it's awesome i can delete cookies for one container and keep the ones i need for work or private separated..best thing ever..

**Comment by VerisZG** [comment]
BUMP - please ADD SORTING the list in the RIGHT CLICK TAB MENU (open with) according to the sorted list in container list management.

**Comment by julie777** [comment]
For those of us using containers and with many containers to keep things isolated there is a real need to be able to manage containers, reorder the list, change the information and rules for a container, and do it in one place.

I use Simple tab groups also and something like its manage tabs page for managing containers would be nice.

**Comment by dannycolin** [comment]
Fixed in #1608. For the right-click menu or urlbar menu, this needs to be implemented in Firefox itself and a bug report has been filed upstream.
