### ISSUE TITLE
Disabling multi-account-containers causes desync

### ISSUE THREAD

**Issue by LoneFenris** [mozilla/multi-account-containers#1650]
- Multi-Account Containers Version: 6.2.1
- Operating System + Version: Arch Linux
- Firefox Version:73.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
After setting up sync in the addon, my containers properly synced. I then disabled the addon momentarily in order to log off a site in the default container. Upon re-enabling the addon, the containers added by sync are gone and have yet to come back even after closing and re-opening Firefox.

### Expected behavior
The synced containers persist through a disabling and re-enabling of the addon

### Steps to reproduce
1. Set up containers sync and see that synced containers have been added
2. Disable Multi Account Containers
3. Re-enable Multi-Account Containers
4. See that the containers added via sync have disappeared

### Notes
I don't know if there's a way to manually initiate a containers sync. I tried initiating a normal Firefox Sync, though that didn't help the situation. I also tried adding a new container to see if that would a trigger a new container sync to re-add the lost containers with no luck.

**Comment by LoneFenris** [comment]
Possibly related to #1413 ?

**Comment by stoically** [comment]
Disabling the last Add-on that keeps the containers feature active resets containers to the default (#1236), but keeps MAC's storage, so when re-enabling the sync potentially might get confused.

**Comment by philipreimer** [comment]
In my case containers and settings were partly restored by synch after re-enabling the addon.

I had setup the Addon and enabled the synch feature.
Then I briefly disabled the containers Addon because I wanted to test if it interfered with another Addon, which apparently reset all settings back to default.
After re-enabling the containers Addon it then seemingly restored part of my container setup from the synched settings.
So I had some of the default containers with empty site lists and some of the containers I had added myself complete with my site list, and some containers I had added but with empty site list.

There should be a warning that disabling the Addon will delete all your custom settings.
Also, when re-enabled the Addon should ask if I want to restore settings from the synched settings or if I want to start configuration from scratch, and not blindly synch back and forth.

**Comment by chrisgraham** [comment]
I recently had to disable all my addons to work out which was causing an issue. A common thing for people to do.

I lost all my settings :(.

I can reproduce trivially.

First:
I can confirm that sync is turned on in the addons settings.
I can confirm Firefox is configured to sync everything, with the exception of addresses.
I can confirm I've had no other problems with sync (I do use multiple machines sometimes, my stuff is always there).

Reproduction instructions:
1) Delete all the default containers but one
2) Force manual sync in Firefox sync settings, just to make sure it has synced
3) Disable the addon
4) Enable the addon
5) Observe the containers are back
6) Force manual sync in Firefox sync settings
7) Observe the containers are still back

Obviously this is showing that deletion of containers isn't working, not containers being lost. Theoretically that could be a separate issue, but I doubt it.
