### ISSUE TITLE
Add ability to close a tab without showing the hidden container.

### ISSUE THREAD

**Issue by bakulf** [mozilla/multi-account-containers#168]
When the user hides tabs, there is not a way to close all of them (or some of them) without showing them  all again.

**Comment by TanviHacks** [comment]
The list of hidden tabs are grayed out (since they aren't clickable).  After discussion in today's containers meeting, we propose that they also have an X on the right hand side of the grayed out lines, so that a user can remove individual tabs that are hidden in a Container.

@johngruen does that sound okay?

**Comment by ChenMorpheus** [comment]
If we want to provide users the ability to close tabs within the list, I would recommend not only offering for hidden containers but also visible containers since it is more consistent and usable for both modes. Please find the mockup below for detailed flow and let me know if any questions, thanks.

![close hide tabs](https://cloud.githubusercontent.com/assets/18019946/22926359/39c8c5a2-f2e7-11e6-8e82-543b06843b24.png)

**Comment by groovecoder** [comment]
@ChenMorpheus - do we have a specific asset for the close "x" button here?

**Comment by TLHuang** [comment]
Attached the close icon. Please set the opacity on hover state to 50, and set to 100 for the active state. Let me know if any questions.

[container-close-tab.zip](https://github.com/mozilla/testpilot-containers/files/815726/container-close-tab.zip)

**Comment by groovecoder** [comment]
Thanks @TLHuang. I'm removing the needs:UX label for now.

**Comment by ShivangiKakkar** [comment]
@bakulf @groovecoder I would love to work on this issue? May I?
