### ISSUE TITLE
Set new tab to always open in specific tab

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#1743]
Right now there is no way to make the new tab always open in a specific container AFAIK.

**Comment by Solid-Ice8** [comment]
This seems to be intended since NewTab is apart of Mozilla page like about:preferences, addon, config.etc.

None of these will be able to be set opening in a specific container. This includes the official Mozilla addons page (addons.mozilla.org) which I've tried setting in a container...and then finding out there was no additional confirmation to set "remember my decision for this site".

**Comment by mope1** [comment]
This extension is unusable for me personally until **new tabs open in the container of the currently selected tab.**

**Comment by dannycolin** [comment]
Duplicate of #356
