### ISSUE TITLE
CTRL+. keyboard shortcut does not work when on a pinned tab

### ISSUE THREAD

**Issue by richardkmichael** [mozilla/multi-account-containers#1758]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: macOS 10.14.6
- Firefox Version: 76.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

```
1Password extension (desktop app required)	4.7.5.90	true	onepassword4@agilebits.com
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.1.1	true	@contain-facebook
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
FoxyProxy Standard	7.4.3	true	foxyproxy@eric.h.jung
Google	1.0	true	google@search.mozilla.org
Octotree	4.2.1	true	jid1-Om7eJGwA1U8Akg@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.27.10	true	uBlock0@raymondhill.net
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Export Cookies	0.3.2	false	{36bdf805-c6f2-4f41-94d2-9b646342c1dc}
LiveReload	20.3.0	false	{076321a9-0b0c-4a3f-8fe8-b22328dfe684}
```

### Actual behavior

While on a pinned tab, pressing CTRL+. (to open the container pane) does nothing.

### Expected behavior

The container pane should open, just as it does on unpinned tabs.

### Steps to reproduce
1. Pin a tab
2. Press CTRL+. to try and open the container panel.
3. It does not open.

**Comment by turdbutt** [comment]
@richardkmichael, can you try pinning some different websites and test the shortcut again?

I just did some quick testing and found that on Google sites like Gmail, Messages and Calendar, the shortcut does not work. On other pinned websites (Plex, Proxmox, GitHub) the shortcut works fine, at least for me on Linux.

I can presume that this is because I have enabled keyboard shortcuts in my Google services and they are overriding Firefox's container tab shortcut. 
In the case of GitHub, having cursor focus in this reply box will also override the container tab shortcut. However, if I click the whitespace, the shortcut works on a pinned GitHub page.

**Comment by richardkmichael** [comment]
@turdbutt Ah, thanks for pointing this out.  I've just tried Gmail, shortcut *did not* work; Calendar *did* work (perhaps I do not have an overriding shortcut enabled); GitHub behaved just as you described.

Even if Multi-containers could override the site shortcuts, it seems doubtful that would be desirable in all cases.  So this would need a preference/setting.  All and all seems a bit complicated/unnecessary for the few "non-working" sites.

Closing.
