### ISSUE TITLE
Containers won't delete it comes back, I have sync turned on.

### ISSUE THREAD

**Issue by ShahariarSayem** [mozilla/multi-account-containers#1799]
I'm new to this, would like some help.

**Comment by sdht0** [comment]
I don't think this is an issue with sync. I turned off sync and tried to delete assigned websites from a container, but they still came back!

**Comment by Yowlen** [comment]
Can confirm. This is a massive issue for those of us that use this in combination with the Temporary Containers addon for extra privacy, since it floods the sync with hundreds of `tmp` containers with no way to permanently delete them unless we give up the ability to use our permanent containers across different devices.

**Comment by jtagcat** [comment]
Duplicate of #1696
