### ISSUE TITLE
Adding Local PDFs to a container "breaks" the container

### ISSUE THREAD

**Issue by dylmye** [mozilla/multi-account-containers#1817]
- Multi-Account Containers Version: 7.0.1
- Operating System + Version: Windows 10 Latest x64
- Firefox Version: Beta 79.0b7 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

<details>
<summary>Extensions</summary>

|Name|Type|Version|Enabled|ID|
|--- |--- |--- |--- |--- |
|1Password extension (desktop app required)|extension|4.7.5.90|true|onepassword4@agilebits.com|
|Amazon.co.uk|extension|1.1|true|amazon@search.mozilla.org|
|BetterTTV|extension|7.2.83|true|firefox@betterttv.net|
|Bing|extension|1.1|true|bing@search.mozilla.org|
|bootstrap-responsiveHelper|extension|1.2.6|true|{76f8f20b-e3bc-44ea-a243-152f71953407}|
|Bypass Paywalls|extension|1.7.4|true|bypasspaywalls@bypasspaywalls.weebly.com|
|Chambers (UK)|extension|1.0|true|chambers-en-GB@search.mozilla.org|
|Cookie Quick Manager|extension|0.5rc2|true|{60f82f00-9ad5-4de5-b31c-b16a47c51558}|
|DuckDuckGo|extension|1.0|true|ddg@search.mozilla.org|
|eBay|extension|1.1|true|ebay@search.mozilla.org|
|Firefox Color|extension|2.1.5|true|FirefoxColor@mozilla.com|
|Firefox Multi-Account Containers|extension|7.0.1|true|@testpilot-containers|
|FrankerFaceZ|extension|4.0|true|frankerfacez@frankerfacez.com|
|Google|extension|1.0|true|google@search.mozilla.org|
|Honey|extension|12.1.1|true|jid1-93CWPmRbVPjRQA@jetpack|
|HTTPS Everywhere|extension|2020.5.20|true|https-everywhere@eff.org|
|JSON Lite|extension|19.6.0|true|{16a49f65-1369-4839-a5ef-db2581e08b16}|
|Markdown Viewer Webext|extension|1.5.0|true|{943b8007-a895-44af-a672-4f4ea548c95f}|
|MetaMask|extension|8.0.4|true|webextension@metamask.io|
|NightTimeFP theme|extension|1.0.1|true|{b3a962bb-594a-488e-ad44-d3e3e7673c67}|
|Open in VLC™ media player|extension|0.2.1|true|{6b954d17-d17c-4a19-8fe6-ee8052a562d6}|
|Pretty XML|extension|0.1.0|true|{dd6008c8-a74c-47ab-8df5-04412a046725}|
|React Developer Tools|extension|4.8.2|true|@react-devtools|
|Reddit Enhancement Suite|extension|5.20.2|true|jid1-xUfzOsOFlzSOXg@jetpack|
|Redux DevTools|extension|2.17.1|true|extension@redux.devtools|
|Refined GitHub|extension|20.7.12|true|{a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad}|
|Stylus|extension|1.5.11|true|{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}|
|Tags for YouTube™|extension|8.4|true|jid0-cBh0nRMLV5BY1dlp33s3g7dFXLY@jetpack|
|TinEye Reverse Image Search|extension|1.4.1|true|tineye@ideeinc.com|
|To Google Translate|extension|4.0.6|true|jid1-93WyvpgvxzGATw@jetpack|
|uBlock Origin|extension|1.28.2|true|uBlock0@raymondhill.net|
|Wikipedia (en)|extension|1.0|true|wikipedia@search.mozilla.org|
|Zotero Connector|extension|5.0.68|true|zotero@chnm.gmu.edu|
|No PDF Download|extension|1.0.6|true|{b9b25e4a-bdf4-4270-868c-3f619eaf437d}|
</details>

### Actual behavior
Opening a local PDF file in a tab, then re-opening it in a container causes the container to break: you can no longer show/hide the container, it will remove the tabs from the open container when you restart the browser and essentially the container no longer works as expected.

### Expected behavior
Local filesystem PDFs can be added and removed from containers without breaking containers, as is the case for remote PDFs and webpages.

### Steps to reproduce
1. Create a container
1. Open a PDF in Firefox, I have tested this by dragging the PDF to the top bar
1. Open a webpage, it doesn't matter the content
1. Re-open both of these in the container by right-clicking the tab and selecting your container in the "re-open in container" context menu
1. Hide the container by clicking on the MAC extension icon, finding the container, and clicking hide
1. Now by following the same instructions as the step above, "show" the container.

You'll notice that the PDF doesn't re-open, and you can no longer hide the container.
![image](https://user-images.githubusercontent.com/7024578/87609390-53e71c00-c6fa-11ea-9059-1b6c54dce99d.png)

Closing Firefox completely (having set Restore previous session in about:prefs) and re-opening, you'll see the content previously in that container are now outside of the container. You can "show" the container again, but again you won't be able to hide it again. The container is therefore "broken".

### Notes

Please let me know if you need a video reproduction of this issue, I'm happy to arrange that.

**Comment by schra** [comment]
I ran into the same issue. This issue is even more general than @dylmye describes it. Actually, it is sufficient to have any kind of local file opened. In my case I had multiple local HTML files assigned to my containers which broke them. Thus I now have to delete and re-assign most of my containers again..

I personally not only experience the problem described by @dylmye but I additionally have the problem that some containers completely (or almost completely) "dissolved" themselves: Some containers are now (after restarting FF) completely empty or only contain one tab - although I assigned something like 50 tabs to each of them. The tabs are still inside my window but they lost the assignment to the container and are displayed without any container association. However, I sadly can't reproduce this behavior of the "dissolved" tabs. I can only reproduce the "broken" containers as described by @dylmye .

Details:

* FF 84.0
* Multi-Account Containers 7.1.0
* All plugins disabled except Multi-Account Containers
* OS: Arch Linux

@dylmye Please rename the title of this issue to "Adding Local **file** to a container "breaks" the container "

@ maintainers: Maybe a good measure against this bug would be to disallow adding local files to a container as long as this bug exists?

**Comment by schra** [comment]
This issue is a duplicate of #918, see https://github.com/mozilla/multi-account-containers/issues/918#issuecomment-360537785

> [Steps to reproduce]:
> 3. Open a "Work" container tab and drag a local file into it.

And #1717 describes the root fo the problem that we experience:

>  Hide/Show tabs in this container actually closes and reopens tabs instead of hiding/showing, meaning it cannot reopen (show) privileged tabs (file, chrome, about, etc.)

**Comment by dylmye** [comment]
Thanks for the info @schra, closing as a duplicate of #1717.
