### ISSUE TITLE
Friction adding a site to a container: requires visiting it after unchecking "Limit To Designated Sites"

### ISSUE THREAD

**Issue by jimaldon** [mozilla/multi-account-containers#1828]
There's a lot of friction when it comes to adding a site to a container. Since there's no option to manually input URLs to the designated sites list, I need to visit a website in the container I need in order to add it to the list. But I'll constantly be kicked out of the container if I have "limit to designated sites" enabled. 

The situation is worse if the site in question is a subdomain which the server is configured to automatically redirect users from. In this case, you can't add it to the list since you can't manually visit it.

**Comment by redbaron-gt** [comment]
Needs manual input of URL for containers functionality. For example I cant add AWS console user URL like https://1234234234.signin.aws.amazon.com/console because it always redirects to different page when entered.

**Comment by adamalton** [comment]
This is very much related to #1830 and #1670

**Comment by sdht0** [comment]
I face this issue as well, when websites redirect to other domains for login/payments and it is very hard to add all the domains to the container.

One idea comes to my mind and should be simple enough to implement. If "limit to designated sites" is enabled and the user/a redirect tries to open a website that is not in the assigned list, the user should get a prompt to either "confirm opening in default container" or "assign domain to this container and continue". This will be especially useful for redirects across multiple "short-lived" domains (some sites do this), which would be difficult to find out and add manually even if #1830 were to be implemented.

A 3rd option could be to "temporarily allow opening in this container" or even "temporarily disable limit to designated websites", e.g., for payments sites, that could be common to multiple other sites, similar to #1834.

**Comment by adamalton** [comment]
I like the suggested solutions above from @sdht0, particularly the first one.

**Comment by blis5fool** [comment]
I'm currently facing this issue for something as simple as clicking print button after opening a PDF from Gmail because it performs several redirects as @sdht0 mentions above.

I also like first suggestion by @sdht0 and I think it would also be helpful to be able to enter URL manually but with wildcard like "*.google.com"

**Comment by grahamperrin** [comment]
> friction 

▶ 2017 issue #719 with multiple duplicates

* in particular, please see https://github.com/mozilla/multi-account-containers/issues/719#issuecomment-825914148

> manually input URLs 

▶ 2017 issue #839 with multiple duplicates

@jimaldon please consider closing this issue so that other issues may be more easily managed. Thank you.

**Comment by grahamperrin** [comment]
Thanks!
