### ISSUE TITLE
Feature Request: Open bookmark link in same container

### ISSUE THREAD

**Issue by shahishasank** [mozilla/multi-account-containers#1908]
When I open a bookmark using mouse middle button(bookmark opens in new tab), it always open in default container of Mozilla.

It would be much better if it opens in same container which I'm using.

Multi-container with random user agent, work like charm. Thank You

**Comment by Sayrus** [comment]
I was going to open a feature request for this as the behavior is different between a simple click and a ctrl+click/mouse3. Great to see someone already did !

To add a bit on this, current bookmark behavior does not match the page behavior.
* Ctrl+Click/Mouse3 inside the page will open a new tab with the active container
* Ctrl+Click/Mouse3 on a bookmark will open a new tab with no container (default or assigned container)

However, I'm not sure the there is currently a way to access this event.

**Comment by dannycolin** [comment]
You should be able to right-click > Open in New Container Tab a bookmark in a recent Firefox version.

I agree that having a different behaviour for middle-clicking a link in a page vs. a bookmark when in a container can break the user expectation. However, this would need to be fixed in Firefox itself. Please file a bug report on bugzilla.mozilla.org for that.

Closing for now but don't hesitate to ask questions if you need clarification on something.
