### ISSUE TITLE
Thousands of Duplicate Containers when Syncing

### ISSUE THREAD

**Issue by criscolord** [mozilla/multi-account-containers#1912]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Win10 20H2, Ubuntu 20.04
- Firefox Version: 83.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
1Password X – Password Manager	extension	1.22.3	true	{d634138d-c276-4fc8-924b-40a0ea21d284}
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.2	true	bing@search.mozilla.org
Disable Facebook News Feed	extension	2.1	true	{85cd2b5d-b3bd-4037-8335-ced996a95092}
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
Enhancer for YouTube™	extension	2.0.101	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	extension	7.1.0	true	@testpilot-containers
Ghostery – Privacy Ad Blocker	extension	8.5.3	true	firefox@ghostery.com
Google	extension	1.1	true	google@search.mozilla.org
Night Owl🔥	extension	0.3.5	true	{74997d71-ea10-4020-921b-47056dd7d28c}
Reddit Enhancement Suite	extension	5.20.9	true	jid1-xUfzOsOFlzSOXg@jetpack
uBlock Origin	extension	1.31.0	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Cisco Webex Extension	extension	1.8.0	false	ciscowebexstart1@cisco.com
Cookiebro	extension	2.18.0	false	{15b1b2af-e84a-4c70-ac7c-5608b0eeed5a}
HTTPS Everywhere	extension	2020.11.17	false	https-everywhere@eff.org
Load Time	extension	0.2.2	false	{f5434366-ae48-4e6c-91b8-370b89487e8f}
Startpage.com — Private Search Engine	extension	1.3.0	false	{20fc2e06-e3e4-4b2b-812b-ab431220cada}

### Actual behavior
Synchronizing produces duplicate entries with identical names and icons.  After I delete the duplicate entries on one machine and sync a new machine, the duplicate entries reappear.  I use Linux/Windows/Mac on various days and when I log into my Linux machines the "Personal" group (which I deleted long ago and don't use) has been duplicated **tens of thousands** of times.  On Windows I'm seeing ~10 "Home" groups.  

On linux I typically edit a file I found with grep to delete the excess entries because it would be impossible to delete them all through the UI.  On Windows I delete the excess through the UI.

### Expected behavior
The container setup on the machine I use last would be the one synchronized to all other machines.  When I start up a machine I haven't used for 6 months, it would get only the latest container set.  It would not contribute its 6-month-old container set to the current set.  Duplicate container names/icons would not be allowed.

### Steps to reproduce
1. Get your database in whatever messed up state mine was in a year ago when I started using this plugin
2. Sync a new browser.
3. It receives literally thousands of "Personal" groups, a dozen "Home" groups.  When I delete them through one means or another, they re-appear next time I sync a machine.  I can't get rid of them and when I do, they just come back.

**Comment by DrewNull** [comment]
Any word on this issue? I've had to disable Firefox Container Sync because not only does it create thousands of duplicate containers, but it pegs my CPU at 15-20% while doing so. Firefox Container Sync is effectively bricked for those of us getting this problem.

**Comment by criscolord** [comment]
@DrewNull sorry to hear it's not just me!  I have had luck uninstalling and re-installing the plugin and syncing it (sometimes it takes several tries), but I still get the duplicate containers on occasion and have to recover again.  Is the issue on Linux for you?  That is where I am seeing the 10k+ container bug.  On Windows and Mac my containers seem to have stabilized.

**Comment by DrewNull** [comment]
Windows here. 

The only way to stop it that I've found is to uncheck Add-ons from the Choose What To Sync setting. Unfortunately this disables syncing for all add-ons. But at least Containers doesn't create thousands of duplicates to manually delete and freeze up the whole browser.

**Comment by timonoj** [comment]
I have this same issue as a result of a bug in Temporary Containers add-on. By now the bug is supposed to be resolved, but to those that we got the cloud storage messed, it really messed it.

In short...seems the sync of all those containers into your cloud storage maxed the storage settings. So now it doesn't allow any further write (even if it's for deleting). So it can only read again and again, the insane amount of tmp containers I have. The only solution I've been given is to "delete my account and recreate it".

Not very helpful...

**Comment by DrewNull** [comment]
Well that's perfectly awful. Thanks for chiming in @timonoj. Hoping we can get official comment from Mozilla...

**Comment by JoelB** [comment]
I am also experiencing this issue and am searching for a solution. I noticed it because new tabs were extremely slow to open. It's taken me a long time to rebuild my Firefox profiles. 

Does anyone know if there is a way to clear all multi-account containers data from your Firefox account to prevent the issue @timonoj described? I'd also be interested in trying to sync a working copy of my MAC data overtop of the existing data to see if the problem recurs or if it was caused by a relatively rare condition.

**Comment by timonoj** [comment]
Ok...This workaround might be working for me. But it's prone to fail again if there's a lingering firefox synced with thousands of those damn containers. ie, if you fix it on one firefox of your account, but some other firefox in a different computer synced also has the containers, you're back to row one. I'd just log off from ALL your firefox first, except for one. In all the others, go to the point of completely removing the profile. 
In the remaining firefox that is still syncing. Stop the container sync in the MAC settings. Then close Firefox. Find the containers.json in the profile folder `/home/your_user/mozilla/firefox/profile/your_user.default user/containers.json` (might need to find your firefox profile path if in Windows)
If you open it, will find an insane amount of lines referencing between brackets to the settings of each container. 
Delete all the lines that are from the tmp containers, making sure your file finishes with `}]}`. As in,
.... `,{"userContextId":16,"public":true,"icon":"circle","color":"toolbar","name":"mylastvalidcontainer"}]}`
Save the file. You can now open the browser. It should hopefully show just the valid containers. But at this point, this is only temporary, and if any sync happens, your config will be messed again.

This is the comment that helped me greatly now:
https://github.com/mozilla/multi-account-containers/issues/1661#issuecomment-591506621

In short...

1. Open extension console: Go to `about:debugging#/runtime/this-firefox`, select "Inspect" on Multi-account Containers, and select the console tab
2. Type `browser.storage.sync.clear();`
3. Manually sync through the browser (hamburger menu, your account, Sync Now)
4. repeat step 2 and 3.
5. To make sure it's working, you can type await `browser.storage.sync.get();`. It should return and empty object if it's working.

In my case and because I disabled the MAC sync at a later stage, the `browser.storage.sync.get();` got me the basic containers I had left. If you get more objects, try repeating again, and make sure you have no tmp containers left in your MAC. 

After this, and to avoid any further messing from the remaining browsers, I deleted the local profile in all of them. I believe if the local storage have containers still stored, it might want to sync those back to the Firefox Sync...and you'd be back at row one. 

Good luck!

**Comment by JoelB** [comment]
Thank you very much @timonoj! I followed your directions and the duplicate containers have now stopped and my sync is working again. I also now know that MAC is storing its containers in the containers.json file so I can keep regular backups of that file in case this ever happens again.

For anyone else experiencing this, you can find a list of devices that are syncing to yoru firefox account by clicking Account Settings -> Manage account in the Firefox hamburger menu and then clicking Show next to "Devices and Apps".

**Comment by milessa42** [comment]
I'd like to chime in and confirm that that the workaround from @timonoj seems to work for my usecase (which does not involve using Automatic mode, so my created temporary containers are small). 

Here are my steps taken:

1. Signed out from all other firefox devices, leaving just my current machine logged in
2. Followed timonoj's workaround, choosing to delete containers.json entirely, and restarted Firefox.
3. Re-configured the base MAC containers to my liking (sadly any deletions here get resynced, that's probably the root problem in the first place!)
4. Reset settings for Temporary Containers (Advanced -> General -> Reset Storage -> Wipe)
5. Gave temp containers all optional permissions (my preference, I don't think its needed)
6. In order to try and create the most limited number of temporary containers possible, I changed these configs:
    1. Under General, set Container Number to "Reuse Available Numbers"
    2. Under General, set Delete no longer needed Temporary Containers  to "After the last tab in it closes"
7. For transparency and posterity, here's my other configs changed for my personal preferences - they shouldn't affect anything but this issue is a mess so better safe than sorry. 
	1. Advanced -> General -> Check "expand all preferences by default"
	2. Advanced -> General -> Popup -> Check "Show icon in the address bar that reveals the popup"
	3. Advanced -> General -> Context Menu -> Check "Show Temporary Container entry in the right click on bookmarks context menu"
	4. Advanced -> General -> Isolation -> Check "Instead of creating a new tab replace the current tab in case of isolation"
	5. Added some isolation entries under Isolation -> Per Domain (I don't use automatic mode, it definitely causes a mess with MAC)
8. Exported Temporary Container settings to Firefox sync (Export/Import -> Export to Firefox Sync)
9. Renabled sync for Multi Account Containers
10. Forced sync for Firefox account
11. Logged into other devices - I deleted profiles or app data depending on which platform (desktop or mobile, specifically), and then re-logged in with my firefox account. For desktop installs, I re-enabled Sync for Multi Account containers, gave all perms to MAC and Temp Containers, then imported the config for Temporary Containers from Sync

At the very least, I think that since i have a more managable container list now, I could backup and manually sync the `containers.json` file if need be, but with my low amount of temp containers and judicious removal of them I don't think many are going to get caught by sync going forward.

**Comment by flanger001** [comment]
I've been using this script to delete the thousands of tmp containers I end up getting every time: https://gist.github.com/flanger001/8fedc4ebddb8627a6994eeca0bb39d4a
