### ISSUE TITLE
addons.mozilla.org managed to always be in a container

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#1917]
I prefer to always have AMO pages in my _Personal_ container. 

Please make this preference effective: 

![addons mozilla org in a managed container](https://user-images.githubusercontent.com/192271/102050027-ee4aa900-3dd9-11eb-8c33-40c346c62fa5.png)

I understand that AMO pages are generally treated as special, but there should be exceptions for sane use cases such as this. 

### Simple workaround: fail

I most often open AMO pages through the search feature at about:addons 

Whilst about:addons can be opened in a _Personal_ tab: 

* search results fail to open in the same container. 

### A more complex workaround

I habitually use [Switch Container](https://addons.mozilla.org/addon/switch-container/) to do what Firefox Multi-Account Containers can not: 

* [addons.mozilla.org in a managed container.zip](https://github.com/mozilla/multi-account-containers/files/5687005/addons.mozilla.org.in.a.managed.container.zip)

**Comment by filikun** [comment]
I thought I had a bug or something when my addons.mozilla.org didn't open in the container I choose for it. 

The Switch container one, you can set Firefox to switch container without opening a new tab. Maybe I got this all wrong but under the addon settings you have "Tab behaviour" "Replace tab instead of creating a new one". So for example if I'm in personal and open an URL that is in let's say banking it jumps over to banking container in the same tab.

**Comment by grahamperrin** [comment]
> list of URL's you have in a container 

That's the _site list_. Click **Manage Containers**, then a container.

**Comment by dannycolin** [comment]
This is a restriction from Firefox itself. There's a preference in about:config named `extensions.webextensions.restrictedDomains` that contains the domains that addons can't manage. You can modify this preference **at your own risk** to allow your addons to work on this websites.
