### ISSUE TITLE
How to  unassign a website from "Always Open in This Container”?

### ISSUE THREAD

**Issue by GildedHonour** [mozilla/multi-account-containers#1920]
How to   unassign a website from "Always Open in This Container”?

**Comment by ameaninglessname** [comment]
As far as i know, you could remove it from site list and re-add it.

**Comment by GildedHonour** [comment]
you could remove it from site list  --> where's that?

**Comment by chenshengzhi** [comment]
1. Go to the website.
2. Right-click anywhere on the page, and open the submenu "Firefox Multi-Account Containers"
3. Uncheck the submenu item "Always open in this container"

**Comment by Cavein** [comment]
Yes!  This would be awesome!  I made many mistakes using this feature, and now I constantly get those "Open this site in your assigned container?" pages whenever I try to go to a URL in a different container, but there doesn't appear to be any way to reset them.   Chenshengzhi's suggestion doesn't seem to work (there's no submenu for multi-account when you right-click on a page) and going through the multi-account button on the menu bar just lets you assign it to another tab (not remove the assignment entirely).  I would actually love a way just to purge/remove ALL of the assigned URL/Container data.  I found where the settings were stored locally and purged them and it seemed to work for a while, but I suppose it synced my data again and overwrote my changes because I'm back to square one.  
A page with all of the assigned URLs and containers with the option to delete them would be a HUGE help.

**Comment by Cavein** [comment]
Oh jeeze, I was reading some other PRs and found the solution:
Click on the MAC button at the top -> Manage Containers -> Pick your container you want to edit -> Manage Site Lists...
From here you can remove any assigned sites for that container!  I'm so happy I found that comment because I haven't seen that link there before and was trying to find a way to do it manually (edit the JSON files, but they kept re-syncing over my changes).

**Comment by JanMouwes** [comment]
> Oh jeeze, I was reading some other PRs and found the solution:
> Click on the MAC button at the top -> Manage Containers -> Pick your container you want to edit -> Manage Site Lists...
> From here you can remove any assigned sites for that container! I'm so happy I found that comment because I haven't seen that link there before and was trying to find a way to do it manually (edit the JSON files, but they kept re-syncing over my changes).

It is not at all clear that that's an option. There should be some sort of indicator that you can click those list items, other than the highlight-on-hover. I've been using this extension for months and I didn't know about it. Maybe a gear or some other icon? I was looking for the site-list on the extension preferences page myself, so maybe there's an option to add a link to the site-list to the preferences page.

**Comment by GildedHonour** [comment]
I haven't been aware about that for years. Bloody container, it really grinds my gears.
