### ISSUE TITLE
Export-Import container names and assigned sites

### ISSUE THREAD

**Issue by drmirk** [mozilla/multi-account-containers#1959]
Right now syncing has some issue. So, an option to manually export/import with current configuration would really help us.

**Comment by Valtarien** [comment]
I second this suggestion. Especially since I would like to erase all my containers and start over, then export my setup in case of future problems. I know I could delete them manually, but I have dozens, if not hundreds, of containers added by the "Temporary Containers" add-in. We need some way to export, import, & reinstall manually.

**Comment by o-l-a-v** [comment]
Sync is so broken right now it would be better to have it disabled.

**Comment by Saimyx** [comment]
I agree, I would also like to have this function. We don't necessarily use firefox sync

**Comment by maxxcrawford** [comment]
Duplicate of #1427
