### ISSUE TITLE
Bind bookmarks to a specific container

### ISSUE THREAD

**Issue by garfildalex6** [mozilla/multi-account-containers#1970]
Good day. Is it possible to bind a bookmark to a specific type of container? So that this particular bookmark always opens in this container.

**Comment by UnpilotedRebuilt1** [comment]
I've recently switched from Chrome to Firefox. Unfortunately Firefox's profile system is far from convenient enough for me to use it to split personal browsing from work browsing. I installed this extension a couple days ago and its working great so far however I would really like to be able to set certain bookmarks to open in a specific container automatically instead of having to right click the bookmark and open it in a specific container manually.

Ideally this option would be added to the bookmark's context menu or at the very least the bookmark's properties. But yes I believe this is a very needed feature and it would definitely be very, very useful to myself.

Thanks for the awesome work developers! I hope this feature request gets implemented!

**Comment by funkybob** [comment]
I too am moving from Chrome, and prefer to keep my bookmarks separate per persona, so they don't even show in other "containers".

This would be a most welcome feature.

**Comment by grahamperrin** [comment]
Duplicate of #854

**Comment by mikenrafter** [comment]
This is possible, using this extension: [Vance-Spears/container_bookmarks](https://addons.mozilla.org/en-US/firefox/addon/container_bookmarks/).

(There are other methods. And I've explored them, but this one's the cleanest so far)

**Comment by mikenrafter** [comment]
I'm currently repurposing two extensions to achieve this functionality in a clean method.  
I'll edit this post when I've something worthy.

**Comment by garfildalex6** [comment]
@mikenrafter thanks! This is what I needed!

**Comment by mikenrafter** [comment]
Glad that works for you. I've finished my extension, which has this same functionality, but does it in a cleaner, more manageable, and far more secure fashion:
https://addons.mozilla.org/en-US/firefox/addon/containmarks/
