### ISSUE TITLE
Clear cookies and all the data only of a certain container(similar to CTRL+SHIFT+DEL) - feature request

### ISSUE THREAD

**Issue by naveen-marthala** [mozilla/multi-account-containers#2006]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
If I clear cookies now, cookies of all websites of all containers will be deleted.

### Expected behavior
Instead, I would like to clear cookies of only certain container.

### Steps to reproduce
1.
2.
3.

**Comment by ameaninglessname** [comment]
[Try this extension, it does have container support](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)

**Comment by gitthehubs** [comment]
@naveen-9697 
I would recommend to install the add-on Temporary Containers (it needs multi-account containers). This add-on automatically creates new temporary containers and deletes the cookies (and more?) from that container when the container is deleted. In the options you can set when the container needs to be deleted, for example after last tab is closed or after X minutes.

https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

Because Temporary Containers is not actively maintained anymore, only big bugs, I created a feature request to include the Temporary Containers in Multi-Account Containers. 😄 
https://github.com/mozilla/multi-account-containers/issues/1973

**Comment by naveen-9697** [comment]
@ameaninglessname, I would like to clear cookies(, cache and everything) of a container, not just by each site.
