### ISSUE TITLE
Search, history, and downloads separated by container tabs

### ISSUE THREAD

**Issue by iaftab-alam** [mozilla/multi-account-containers#2051]
Hey,

I am big fan of multi-account containers extension. After using it for more then a years, and recently i felt there is a need to have this nice feature. That is to have a custom search, history and download settings for each container. I searched and stumble open on this [post](https://discourse.mozilla.org/t/custom-history-settings-for-each-container/14485) from mid-2017, and further I can see that other issues are still open from #318 and #47. I was wondering if there is any progress is made on this. I mean if its possible put in the pipeline and get this awesome feature for such awesome extension.

Regards,
Affi

**Comment by dannycolin** [comment]
For history, see [bug 1283320](https://bugzilla.mozilla.org/show_bug.cgi?id=1283320)

Search and downloads would also need to be implemented upstream (Firefox itself) if the feature request is approved. For this, you need to file a bug report on https://bugzilla.mozilla.org.

Closing since we can't do anything on our side.
