### ISSUE TITLE
The color of the tabs is missing FireFox 89 when the menu bar is hidden

### ISSUE THREAD

**Issue by toopac** [mozilla/multi-account-containers#2063]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Windows 10 19042.868
- Firefox Version: 89.0

### Actual behavior
With the menu bar hidden, the container tabs are not colored anymore (so they cannot be differentiated )

### Expected behavior
The tab should have some kind of color on it to be identified even without the menu bar 

### Steps to reproduce
1. Hide the menu bar
2. Open a tab in a container
3. The color of the container is not visible

**Comment by mihugo** [comment]
With the redesign of Firefox tabs when the browser is in full screen mode and that same screen is being shared with Microsoft Teams (as well as other screen sharing apps that also add a border around the screen being shared) the single thin line is now hidden behind the screen sharing border.  

(this is probably a different specific problem than the one being reported but since it should be considered when redesigning how the tab color's work, I'm adding it here instead of creating a new issue)
I suggest either moving it back down to the bottom of the tab or making the entire tab a color.
I do like that there is now a secondary indicator once you in a tab so even when it hidden one can still verify what tab one is in.

**Comment by mordecai98** [comment]
I see it at the top of the tab and it is very thin and difficult to see.
If the background of the tab was filled with the color or at least a thinker line, it would be more visible.
Here is a screenshot: https://imgshare.io/image/image.pPB908

**Comment by dannycolin** [comment]
@toopac @mordecai98 do you still have this issue in the latest Firefox version?

@mihugo: Your issue is slightly different but same question can you still reproduce it in the latest version?

**Comment by toopac** [comment]
@dannycolin No it's ok on v108

**Comment by achernyakevich-sc** [comment]
@mihugo I have solved similar problem by changing how tabs are styled. I just moved container coloring stripe to bottom of tab.

See https://www.userchrome.org/firefox-89-styling-proton-ui.html#tabstyler for the detailed instruction. :)

In my browser tabs looks like:
![image](https://user-images.githubusercontent.com/24388336/208752460-f030dcc4-3df2-4547-9102-4db84d9cb096.png)

@dannycolin BTW: maybe we could make configurable in MAC settings should be container color line on tab be at the top or at the bottom and how bold it should be. It would be really nice feature. Let me know if you agree - I would create an issue for this feature.

**Comment by dannycolin** [comment]
This line indicator is rendered by Firefox itself and Multi-Account Containers has no control on it. Since it still is an issue, could you open a bug report at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Theme. This should make sure the right people are notified about it.

If possible, please provide your OS, Firefox version and a screenshot without any userChrome.css modifications in the bug report. Also, if you can share the bug report link here, it'd be greatly appreciated.

**Comment by mihugo** [comment]
created issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1806732

Appreciate you follow through on this.
