### ISSUE TITLE
Deleted containers reappearing

### ISSUE THREAD

**Issue by sunsetbrioche** [mozilla/multi-account-containers#2076]
Multi-Account Containers Version: 7.3.0
    Operating System + Version: Windows 10 Pro 19041.1052
    Firefox Version: 89.0.2
    Other installed Add-ons + Version + Enabled/Disabled-Status: None

    Actual behavior
    Deleted a container. After a few days, multiple of the deleted container reappeared in the list.

    Expected behavior
    After deleting the container, that's it.

    Steps to reproduce
    1. Delete the desired container
    2. Reopen Firefox
    3. Check multi-account containers

    Notes
![image](https://user-images.githubusercontent.com/86792284/124159661-fd6f1b00-dacd-11eb-9fc5-80ade0c43c50.png)

**Comment by ecureuill** [comment]
I'm facing the same issue, but instead of days, deleted containers reapears in minutes. I disabled the sync feature to avoid this issue.

Operating System + Version: Debian Bullseye
Firefox Version: 90.0.2
Other installed Add-ons + Version + Enabled/Disabled-Status: Temporary Containers 1.9.2

**Comment by benediktms** [comment]
I'm having the same issue, disabling sync will stop containers from re-appearing, but that does not seem like a fix. Seems like there should be functionality to choose if you want containers to sync by overriding from local or restore to local containers.

**Comment by Yowlen** [comment]
This has been a bug in some form or another for quite a while, unfortunately, and a rather important one, at that. Why it hasn't been fixed quickly, I have no idea, but it can be traced back to at least March of 2020 with #1696 near as I can tell.

I haven't had sync enabled for quite some time because otherwise it'll just flood my list with a bunch of tmp containers that are created by the Temporary Containers addon that I use in combination with this one for extra security and protection against trackers.

**Comment by benediktms** [comment]
The worst thing about this issue is that you cannot even delete the containers manually. It seems that the sync feature has trouble replacing remote content with the local content. At least for the JSON that contains the container metadata.

**Comment by iverik-no** [comment]
> The worst thing about this issue is that you cannot even delete the containers manually. It seems that the sync feature has trouble replacing remote content with the local content. At least for the JSON that contains the container metadata.

Not only that, but in my experience, if you try to delete a container, the sync somehow duplicates the container, and you'll end up with a ton of duplicates. 

It's kinda like that when you delete a container, the sync will download the old settings file (because the one locally is "wrong" now) to give you the "missing" container, and then uploads the "new" settings, to keep it up-to-date. The new settings contains the "new"-old container (the one you tried to delete, but got back because the sync found is missing locally). This "new"-old is added to the list of containers in the cloud, and then you get both in your sync.
