### ISSUE TITLE
Exporting containers 

### ISSUE THREAD

**Issue by akasaka99** [mozilla/multi-account-containers#2093]
Since the sync always fails and repeatedly deletes containers and its associated urls, how can we export the containers and associated urls?

**Comment by zpthree** [comment]
Yes please. I just downloaded Firefox Nightly and it completely reset my containers in Developer Edition 😒.

**Comment by dannycolin** [comment]
It is a known issue that needs to be fixed in Firefox. We don't know when the Firefox developer will fix it but when it happens we'll update #1236. For the import/export functionality, there's already a feature request in #1282 but there's currently no plan to add this feature in the near future. Closing this issue in favor of the 2 others mentioned above to avoid duplicates and really sorry for the inconvinence. I'm also a user (and volunteer) and got bite more than once by that bug :(.
