### ISSUE TITLE
Feature request: Have "Always open this site in..." distinguish between different paths in domains (foo.com/pathA vs foo.com/pathB)

### ISSUE THREAD

**Issue by hub2git** [mozilla/multi-account-containers#2096]
I appreciate how useful multi-account-containers is. It's one of several reasons I love Firefox. 

I suggest enhancing the "Always open this site in [specific container]" feature.

Currently, this feature can distinguish between domains, but it cannot automatically use different containers for different paths of the same domain.

When I go to reddit.com/r/someSubredditA, I want this extension to automatically use my "SeriousFace" container
When I go to reddit.com/r/someSubredditB, I want the extension to automatically use my "HappyFace" container.

Currently, it can't do that, and would open all reddit.com sites in the same container.

If I got my wish, "Always open site in..." would be renamed to "Always open path in..."

**Comment by okeegan** [comment]
Seconded, this drives me crazy with my multiple google accounts!

**Comment by achernyakevich-sc** [comment]
It looks it is another one duplicate. I would propose to try the way described in [the comment](https://github.com/mozilla/multi-account-containers/issues/2100#issuecomment-900967202).

@hub2git Could you close this issue to point other who will search for similar but more structured issue. :)

**Comment by hub2git** [comment]
@achernyakevich-sc Hi Alexander, thanks for your comment on my issue-thread.  Are you sure it's a good idea to close my issue?
My issue is number 2096, yet the tread you linked to is newer (2100).

**Comment by achernyakevich-sc** [comment]
@hub2git This is not about a number but about number of comments and exposed solution. :) For sure you could keep your issue open but I think everybody will just ignore it as there are dozens of this kind issue in this repository and people just ignore because of this fact. I could suspect you even created your issue have not read older closed threads for the same topic. So having one issue will really to help to concentrate on the real solution and comments why MAC developers will never implement it.

You could close is and leave the last comment that discussion moved to the #2100 thread so anybody who will come to your issue will switch there and continue there.
