### ISSUE TITLE
Does multi-account-containers use the plugin-container process?

### ISSUE THREAD

**Issue by hcientist** [mozilla/multi-account-containers#2135]
Does this multi-account-containers extension use the `plugin-container` process?

I cannot seem to eject my eGPU due to instance(s) `plugin-container`. I cannot find recent info about this process on the web, and as I have few extensions running, I was wondering if it might be due to this extension.

**Comment by dannycolin** [comment]
All addons run in the WebExtension child process (See: https://firefox-source-docs.mozilla.org/dom/ipc/process_model.html#webextensions). Since this isn't specific to how this addon works, I'd invite you to [ask your question on #addons:mozilla.org room on our Matrix server](https://matrix.to/#/#addons:mozilla.org).

If you've never used Matrix before, we have a quick introduction guide on https://wiki.mozilla.org/Matrix.

Closing for now.
