### ISSUE TITLE
can't we find a better way to sync containers accross hosts?

### ISSUE THREAD

**Issue by changemenemo** [mozilla/multi-account-containers#2155]
Hi,

I am wondering after all this time that have actually gone wrong several times like the https://github.com/mozilla/multi-account-containers/issues/1912
Can't we find a better way to sync containers between all the hosts? 
I don't know the other users of firefox but I have multiple hosts including VMs. And Those hosts don't have the same capabilities each and everyone of them. So they can't handle all the addons that my powerfuls ones do. 

The fact that you push people to activate the addons sync in the firefox settings just to get the containers list updated.... Isn't it a bit .... unefficient? 

It would be better if the settings of an addon would be store ine the cloud of firefox too. There would be a line in the settings of firefox to sync settings. And then the present addon on the host would verify if there is a section about it and so sync with this section....

That would be I think a more efficient way to proceed. ...

**Comment by dannycolin** [comment]
> it would be better if the settings of an addon would be store ine the cloud of firefox too.

We can't store everything in the Firefox cloud because the webextension api as a low storage limit (See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data). 

> I am wondering after all this time that have actually gone wrong several times like the https://github.com/mozilla/multi-account-containers/issues/1912

This has been recently fixed and will be available in the next release.

I'm now closing this issue since it's more a question than a specific bug report or a feature request.
