### ISSUE TITLE
Container can get into state where it cannot be hidden

### ISSUE THREAD

**Issue by ptomato** [mozilla/multi-account-containers#2233]
- Multi-Account Containers Version: 8.0.2
- Operating System + Version: Fedora 34.20211126.0 (Silverblue)
- Firefox Version: 94.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Canadian English Dictionary	dictionary	3.1.3	true	en-CA@dictionaries.addons.mozilla.org
Adblock Plus - free ad blocker	extension	3.11.4	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	extension	1.9	true	amazon@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	8.0.2	true	@testpilot-containers
GNOME Shell integration	extension	10.1	true	chrome-gnome-shell@gnome.org
Google	extension	1.1	true	google@search.mozilla.org
LastPass: Free Password Manager	extension	4.85.1.3	true	support@lastpass.com
PhpReport timer	extension	0.8	true	{ac78aec1-af40-480d-b4ab-7889b9e5e982}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
English (CA) Language Pack	locale	94.0buildid20211119140621	true	langpack-en-CA@firefox.mozilla.org

### Actual behavior

I use Multi-Account Containers to separate my personal and work browsing, and to be able to close down my work tabs at the end of the work day and resume them from where I left the next work day. (I'm mentioning this because the frequency with which I hide and show containers might be different from the expected usage patterns of this extension, as well as it might be more important to me than to other users that I don't lose the tabs in a container.)

About once every two months or so, one of my containers gets into a state where it is open and has a bunch of tabs open, but I cannot hide it from the container's menu in the extensions area. The menu will still say "Show this container" instead of "Hide this container". If I click "Show this container" then nothing happens.

If I close all the open tabs in the browser window, then clicking "Show this container" will re-open all the tabs, but the menu item will still not change to "Hide this container", and subsequent clicks on the menu item will still do nothing. Restarting Firefox does not fix the broken state of the container. The only way I've found to get out of this state is to write down which tabs are open, delete the container, create a new one, and manually reopen all the tabs in the new container.

### Expected behavior

If any tabs are open in that container, the container's menu should say "Hide this container". If no tabs are open in a container, the menu for that container should say "Show this container".

### Steps to reproduce

I'm not sure what triggers this and I'm not able to reproduce it regularly.

**Comment by drien** [comment]
This has been happening to me periodically for a while, and through some research in old issues on here and in the code I've been able to reproduce consistently:

- Open a local file in a container tab (e.g. `file://...`)
- Hide the container
- Show the container

The addon saves the `file://` url to the list of hidden tabs, but when trying to reopen runs into an Illegal URL error, which interrupts the process of showing the tabs. Since there are lingering hidden tabs, the addon UI only reflects the "Show" behavior.
![image](https://user-images.githubusercontent.com/2391118/219446849-58e6e6bf-3703-40fc-ae55-421567638750.png)

Related issues: https://github.com/mozilla/multi-account-containers/issues/918 https://github.com/mozilla/multi-account-containers/issues/1817

Previous PR closed unmerged: https://github.com/mozilla/multi-account-containers/pull/1927

I've tested the fix above and will open an identical PR momentarily.
