### ISSUE TITLE
Container tabs is not very distinguishable in firefox

### ISSUE THREAD

**Issue by soredake** [mozilla/multi-account-containers#2253]
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: Windows 11 Pro
- Firefox Version: 95.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
![изображение](https://user-images.githubusercontent.com/5204968/147670669-8b6a38a9-2c0f-485b-9d80-ef81d581916a.png)
Right now container tabs are not very distinguishable, especially on big screens or tn monitors where colors are dull.

### Expected behavior
Having container tabs better distinguished. For example tab grouping is done well in chrome in this regard

![изображение](https://user-images.githubusercontent.com/5204968/147671023-d0e9f2cd-9144-4a9c-b2e1-00af8fc54953.png)

### Steps to reproduce
1.
2.
3.

**Comment by dannycolin** [comment]
Sadly, the visual element to distinguish a containerized tab is something that is managed directly in Firefox and not in this addon. Since we can't solve this on our end, I will close this issue. 

However, I invite you to open a bug report on the Firefox bug tracker at https://bugzilla.mozilla.org. You can also read their guideline to file a good bug report on their platform at https://bugzilla.mozilla.org/page.cgi?id=bug-writing.html.
