### ISSUE TITLE
Button is confusingly labeled "Open in Container", in the "Open this site in your assigned Container" splash-page

### ISSUE THREAD

**Issue by dholbert** [mozilla/multi-account-containers#2257]
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: Ubuntu 21.10
- Firefox Version: 97.0a1 (2021-12-31) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: Can supply if needed

### Actual behavior
See screenshot below - in the confirmation splash-page, my two available options are labeled `Open in Container` and `Open in Banking Container`. These options sound like the same thing (one just more specific than the other).

### Expected behavior
The first button should be labeled "Open in Default Container" or something along those lines, instead of "Open in Container".

### Steps to reproduce
1. Open a new tab in the Banking container.
2. Visit https://citi.com (for example)
3. Right-click the page and choose "Firefox Multi-Account Containers | Always Open in This Container"
4. Open a new tab in your default container, and visit https://citi.com there.

### Notes

Screenshot:
![image](https://user-images.githubusercontent.com/426803/147844697-e12e99aa-e765-4796-8314-2550c0f2693e.png)

**Comment by Bilge** [comment]
Moreover, _Remember my decision for this site_ does not work with the _Open in Container_ button at all. That is, you cannot opt out of any site that has become opted in for always opening with a particular container. It is forever stuck in this configuration.

**Comment by achernyakevich-sc** [comment]
It looks you are misled by this UI. In reality it has different intentions - confirm that having previously selected default container you didn't do it accidentally. So checkbox state will be saved *only* to prevent asking next time if you confirm that dedicated container should be used for this site.

Managing list of sites that container will be open by default is available in other places. See https://github.com/mozilla/multi-account-containers/issues/1730#issuecomment-997712373 and comments above.

BTW: It looks like your issue is a duplicate of similar so if my advises helps you it could be good if you will close this issue. :)

**Comment by dholbert** [comment]
Thanks for the comments, but let's maybe move those discussions to other github issues -- the checkbox behavior (and presence of this interstitial) is orthogonal to what I filed this particular github issue about.

I filed this issue here *specifically* about the fact that the label `Open in Container` is confusing/misleading in this UI, since it actually opens the site in your default environment, i.e. not-in-a-container.

**Comment by achernyakevich-sc** [comment]
I just exposed as current reality looks like. Now, having definition of what is it we could propose other labels that will explain reality. So authors of add-on will easier make decision either accept proposal or reject. :)

Or even propose more radical changes to splash-screen UI.

**Comment by flodolo** [comment]
Probably a duplicate of #2168

**Comment by dholbert** [comment]
Indeed, thanks. Closing dupe of #2168.
