### ISSUE TITLE
List of containers broken in overflow menu

### ISSUE THREAD

**Issue by gwarser** [mozilla/multi-account-containers#2262]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

Not all containers are listed most of the time when add-on button is in overflow menu.

### Expected behavior

Full list should be shown all the time.

### Steps to reproduce
1. right click -> pin to overflow menu
2. click the overflow menu
3. click the add-on button

### Notes

https://user-images.githubusercontent.com/886325/148644376-0aee029d-3c36-4ebf-9c75-22f238d96bff.mp4

Name 	Firefox
Version 	97.0a1
Build ID 	20220108005127
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0
OS 	Linux 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021
MAC Version 8.0.4

**Comment by dannycolin** [comment]
Closing since Firefox 109+ won't allow extensions in the overflow menu. There's a new Extension Unified Menu (See https://support.mozilla.org/en-US/kb/unified-extensions) where all addons will be listed. From there, clicking an addon in the list will open the addon popup directly instead of wrapping it inside the menu popup. This removes the issue mentioned in this bug report.
