### ISSUE TITLE
Sites that are set to always open in a specific container lose history if an actual container change occurs

### ISSUE THREAD

**Issue by nagisa** [mozilla/multi-account-containers#2284]
- Multi-Account Containers Version: 8.0.5
- Operating System + Version: NixOS
- Firefox Version: 99.0a1
- Other installed Add-ons + Version + Enabled/Disabled-Status: not relevant, probably.

### Actual behavior

I can't click the back button to return to the previous page.

### Expected behavior

I should be able to click the back button to return to the previous page.

### Steps to reproduce
1. Go to `news.ycombinator.com` in a non-container tab, click a link to a first external website. Reopen the resulting page in some container and set it up to always reopen pages from that domain in the container.
2. Open a new tab, go to `news.ycombinator.com` and click the link to that same website.
3. Try to click the button to go back. It will be grayed out.

### Notes

This is probably caused by the fact that “always reopen in container” behaviour closes the previous tab and opens a new, containerized one. It should preserve the history from the closed tab somehow.

**Comment by dannycolin** [comment]
This is expected because like you mentioned the original tab is closed and a new one is created in the assigned container. 

Currently, the WebExtension API in Firefox doesn't support sharing the history in this scenario. I don't think this is something that'd be accepted as a feature request since the main goal of containers is to completely isolate different "environments".

However, if it was to be considered, it would need to be proposed on bugzilla.mozilla.org because this needs to be implemented directly in Firefox.

Closing for now since there's nothing we can do on our side (the addon) to solve this.
