### ISSUE TITLE
Bug: When a site is configured to always open, opening a bookmark with a specific container doesnt work.

### ISSUE THREAD

**Issue by Hobbit44** [mozilla/multi-account-containers#2345]
-  Multi-Account Containers Version: 8.0.7
-  Operating System + Version: Windows 11 Pro 22593.1
-  Firefox Version: Nightly
-  Other installed Add-ons + Version + Enabled/Disabled-Status: N/A

Steps to reproduce
- Save site as bookmark
- Set site to Always open in container A
- Right click the bookmark and say "open in container B"

Actual behavour:
It still opens in the container A

Expected behaviour:
Link opens in container B

**Comment by chrisbudden** [comment]
I have a silmiar issue - this is my use case -

I have 'portal.azure.com' set to open in a sepcific container as this is primarialy where I need to use Azure, but sometimes i need to use Azure in another container with a different account. If i specifically open a new tab with the secondary container and load the URL, it changes to the primary container rather than the secondary.

Thanks.

**Comment by dannycolin** [comment]
That'd be the expected behavior of the addon. There's already #1133 that is asking the context menu has priority over the "Always open in Container X" option. So I'll close this issue as a duplicate of it.

**Comment by dannycolin** [comment]
Duplicate of #1133
