### ISSUE TITLE
Provide a way to fetch container names

### ISSUE THREAD

**Issue by sindresorhus** [mozilla/multi-account-containers#2361]
I maintain this [browser picker app](https://sindresorhus.com/velja) and I would like to integrate it with Firefox containers, so users can define that certain links should open in specific containers. However, I need to be able to fetch a list of containers so the user can pick one in the user-interface.

Possible solutions:

- AppleScript
- Bundled command-line tool
- [`x-callback-url`](http://x-callback-url.com): `firefox+container:x-callback-url/list?x-success=velja://x-callback-url/container-list`

**Comment by dannycolin** [comment]
Containers (a.k.a contextual identities) are a feature built-in Firefox and Multi-Account Containers is simply a front-end to manage it. So I'm going to close this issue since we can't do anything to (directly) to solve your issue.

However, I can give you some information and a tl;dr of a possible solution :). The information about containers can be accessed with the WebExtension API (See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/). So a solution could be to create a Firefox addon that use `browser.contextualIdentities.query()` to get the container information and then use the Native Messaging API (See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to communicate this information with your external program.

I hope this will help you. Feel free to ask more questions on this thread even if I change to status to "closed" and I'll try to answer them. You can also get help on our Matrix chat server (https://chat.mozilla.org) in the [#addons:mozilla.org](https://matrix.to/#/#addons:mozilla.org) room.

**Comment by webdev69420** [comment]
+1

**Comment by sindresorhus** [comment]
@dannycolin Thanks for explaining 🙏

**Comment by sindresorhus** [comment]
Moved it to a Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1774128
