### ISSUE TITLE
Summary of domain management issues

### ISSUE THREAD

**Issue by kurahaupo** [mozilla/multi-account-containers#2378]
The assignment of domains to containers is a great idea, but there are numerous shortcomings in the current implementation, and the handling of the related reported issues has become very fragmented, with tickets being closed as "duplicate" after extended periods of discussion, often without clarity around whether the underlying issue has been or will be resolved.

So far the accepted solutions have focused on wildcards and/or ancestor domains. As I hope to illustrate here, those only solve _some_ of the problems.

I was prompted to create this issue when #1833 was closed, as [my comment there](/mozilla/multi-account-containers/issues/1833#issuecomment-907741666) still need tracking.

1. Pages may redirect through a domain outside the container, and it's not possible to get a stable page load in the other domain, there's no opportunity to add its domain to any container.
1. Because of this, `Limit to Designated Sites` is almost useless. When the user lands on a page that requires an authenticated session, it may redirect to another page to get the user to log in; if they're already authenticated there, they immediately get redirected back.
   **When those two pages are not in the same container, this can result in an endless loop.** (see #640 & #1335)
   This is particularly problem for any sites that use generic OAUTH between unrelated domains.
   This is also problem with larger service providers with many TLDs. For example, Google has <tt>google.<i>something</i></tt> and <tt>youtube.<i>something</i></tt> registered in most top-level domains (hundreds),  and more than 50 subdomains for products, each of which redirects to an `account.` subdomain (usually but not always in `.com`) when it requires authentication.
1. Having to load the first page from a domain _without_ container protection exposes the user in the very way that containers are intended to prevent (see #719), so we need a more prophylactic ("guard in advance") process (see #1317).
1. Having to load a page and then add the domain is quite slow and cumbersome when dealing with a large number of related domains, so we need a reasonable bulk handling process.
1.  Pages may include components in domains outside the container, particularly JS. Without using the "Network" inspector in the Developer Tools, this can be quite hard to find. We need still need "open this page in container", but it should offer _all_ the domains connected to this page, not just the top-level one.

I believe we need all of these:
   * manual addition of domains (see #839, #1057, #1180, #1227, #1501, #1670)
   * ancestor domain grouping (see #1833);
   * pattern matching (see #691, #1991);
   * allow domains to be opened in _multiple_ containers while not allowing them in _all_ containers, especially those that act as (X)OAUTH providers (see #837);
     * ideally, this would be separate from a _preferred_ container for the domain, and
     * would only permit page to be loaded from a domain where the referrer was already in the container;
   * automated or confirmed addition of redirection domains;
     * same, but with white/black lists;
   * automated or confirmed addition of domains for components (img, js, css, iframe, etc)
     * same, but with white/black lists;
   * a mode where every time you visit a new site, it asks which container to open it in, even when "not in a container" (in the default container).

I note the connection with issues #640, #691,  #719, #837, #839, #1057, #1075, #1180, #1227, #1317, #1335, #1501, #1670, #1784, #1833, #1991.

I note the connection with pull requests #1500, #1627, #1688, #2033, #2114, #2352.

**Comment by kurahaupo** [comment]
@dannycolin as per your suggestion in #1833

**Comment by dannycolin** [comment]
I suggested you open an issue **only** if one specific use case isn't covered by another issues. A summary isn't a specific use case pointing connection to other issues and meaning those problems are already addressed there. Also, this issue doesn't follow the bug report template that is mandatory.

**Comment by kurahaupo** [comment]
Rather than closing the issue, perhaps it could be recategorized as a feature request or a meta issue?

**Comment by dannycolin** [comment]
I do understand and appreciate your concern about not losing sight of *all* the use cases. I also want to point out that closing an issue as duplicate doesn't mean we forgot about things that have been said in the closed thread. 

When someone will work on a feature request, they will also have a look at the duplicates to make sure their solution covers the use cases mentioned in them. Of course, in the limit that the developers judge acceptable because *in rare cases* some use cases can't be implemented for multiple reasons: lack of time or resources to include all of them, harmful features and so on.

If a use case isn't implement by lack of resources or by accident (even if the latter is very rare), we'll be more than happy to fill a report for this one. But again, this isn't something that happens a lot.

Also, keep in mind that I'm doing all that on my free time as a volunteer who like you wanted to see more development happening on Multi-Account Containers so I do have at heart this project. If you still have questions don't hesitate to ping me on our Matrix server in #containers:mozilla.org or in a direct message if you prefer to keep the discussion private.

You can find instruction on how to join on Matrix server at https://wiki.mozilla.org/Matrix

**Comment by xanoni** [comment]
Workaround that helps with some of the redirection issues described in various tickets: https://github.com/mozilla/multi-account-containers/issues/1670#issuecomment-1416926881
