### ISSUE TITLE
privacy.resistFingerprinting Dark Mode doesn't work

### ISSUE THREAD

**Issue by Kurotaku-sama** [mozilla/multi-account-containers#2392]
### Before submitting a bug report

- [x] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

When you have privacy.resistFingerprinting set to true, than it can't detect the device color and its always white.
Even setting the dark mode in firefox itself doesn't work

### Actual behavior

The color is always white when privacy.resistFingerprinting is enabled

### Expected behavior

It should use the Firefox setting for the theme

### Provide a copy of Troubleshooting Information page

```plain text
-
```

**Comment by dannycolin** [comment]
This is the expected behavior when `privacy.resistFingerprinting` is set to `true` in the current release. There's nothing we can do to auto-detect the theme in this situation. 

However, we already have a fix for that in the coming release. There'll be an option in the addon preferences to manually select a theme.
