### ISSUE TITLE
Confirmation page styling is missing

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/multi-account-containers#2441]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

0. on Firefox Nightly
1. Open a web page that defaults to open in a container
2. navigate to said website

### Actual behavior

See screenshot (unstyled error page):
![image](https://user-images.githubusercontent.com/5418775/199737207-c101dea9-b7b9-413f-984d-9021e168d4c4.png)

### Expected behavior

I was expecting the web page to be styled

### Additional informations

I believe that aboutNetError was either refactored or the access criteria for websites have changed. I recommend incorporating the actual required stylsheets directly into the addon.

**Comment by EmirLogas** [comment]
Same issue for me after update to Version 107.0 (64-bit).

**Comment by reedijkbart** [comment]
Same here, since update v107.0 (64-bit)

**Comment by nabeelr** [comment]
Me as well! Same as the rest, since 107.0 on windows, 64bit.

**Comment by nabeelr** [comment]
Any update on this? Some communication would be great.

**Comment by dannycolin** [comment]
If all goes well, we'll push a new release this coming week. 

I also want to emphasize and reassure everyone that this bug doesn't break any functionality in the addon and is purely esthetic.

**Comment by nabeelr** [comment]
Thanks for the update, it's much appreciated. 🙏

While it's not breaking any functionality, it being such a high visibility bug with a core part of the user-interface, it makes it look like Multi-Account Containers has been abandoned, or like there is something bigger wrong.

I could see a lot of users jumping through a lot of hoops thinking something is broken on their end, trying to fix it, and not getting any resolution.

So it makes it a really bad experience for the average user who doesn't know enough to check Github, or that Github even exists, which, aside from eroding the trust in the user, it in turn makes the project look bad, and devalues all the hard work that you guys are putting in. (Hard work which is greatly appreciated by those in the know!)

As someone who loves Multi-Account Containers, as I'm sure everyone on here does, I want it to be successful and want to see wider adoption of what is a really good idea. However, since most people don't know to check Github and their knowledge of the tool ends at the user-interface, leaving aesthetic bugs like this doesn't present the hard work the team on here has put in well to the average user, even-though the average users position may be unfounded.

Anyways, thanks so much for the update, it is very much appreciated!

**Comment by mmtechslv** [comment]
Same on: 
Firefox version - 107.0 (64-bit) 
Fedora 36

**Comment by dannycolin** [comment]
Fixed in 8.0.9. If you have auto-update enabled, you should probably already have it. If not, you can always force an update. See https://support.mozilla.org/en-US/kb/how-update-add-ons for the instructions.
