### ISSUE TITLE
Add default focus to search input

### ISSUE THREAD

**Issue by frnk01** [mozilla/multi-account-containers#2493]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Open container selection. No focus on search input.

### Actual behavior

No focus.

### Expected behavior

I want the search input to be focused when I open the container list.

**Comment by dannycolin** [comment]
While implementing this feature, I read on autofocus and found that it's problematic for users with screen readers. Knowing that, this isn't something that we'd set as a default.

However, we could implement an alternative commonly used in other softwares/websites. Typing "/" while the panel is open should focus the filter box. We already use a similar technical to quickly open one of the top 10 containers in the list by typing a number from 0 through 9.

**Comment by bob27aggiustatutto** [comment]
Or you can implement an option so each user can choose if the autofocus is on or off. Defaulted to whatever you want

Pressing '/' each time is boring

**Comment by unhammer** [comment]
On Norwegian keyboard (linux), you get `/` by hitting `shift+7`, and after hitting `Ctrl+.`, that opens container 7 instead of focusing the search field. 

So I guess the code that's supposed to handle `/` is never reached because the number-shortcuts code uses the physical `KeyboardEvent.code=="Digit7"` instead of `KeyboardEvent.key=="7"` or whatever.
