### ISSUE TITLE
History is lost when opening site container

### ISSUE THREAD

**Issue by fwsmit** [mozilla/multi-account-containers#2547]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Open a site
2. Navigate to some other site to create a history (you can go back by pressing the back button)
3. Use option "Reopen this site in container"

Another option to reproduce is choosing "Always open this site in container". This does it automatically and is the actual thing that bugs me.

### Actual behavior

You cannot press the back button to go to the previous site

### Expected behavior

The history is preserved and you can use the back button to go back.

### Additional informations

This behavior is annoying when having "always open site in" enabled for frequently visited sites. You are unable to go back to the previous site when clicking a link.

The proper way to solve this would be to preserve the history and also remember which site was opened in which container. So if you click a link, the site should open in the assigned container and if you click back, the site should open in the previously used container.

**Comment by dannycolin** [comment]
A container does not have access to other containers because this would leak informations that the website could get access to. This behavior is implemented in Firefox itself and so we cannot modify it in Multi-Account Containers. Feel free to open a bug report on bugzilla.mozilla.org. 

As an alternative, you can make sure "Replace tab instead of creating a new one" is unchecked in Multi-Account Containers preferences:

1. Go to about:addons
2. Click on Multi-Account Containers in the list
3. Go to "preferences" tab 

![image](https://github.com/mozilla/multi-account-containers/assets/7339076/f9944c80-8424-4f84-a731-98b419a8927c)
