### ISSUE TITLE
Long container name in URL bar truncated in Firefox =127.0

### ISSUE THREAD

**Issue by itai590** [mozilla/multi-account-containers#2641]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Upgarde to Firefox 127.0
2. Open a new tab in the container with a long name 

### Actual behavior

The container name is not fully displayed in the URL bar as before
for container name: 'research-rooms-management staging aws-role'
Only this will be displayed
'research-rooms ...'
<img width="1020" alt="Screenshot 2024-06-17 at 20 17 23" src="https://github.com/mozilla/multi-account-containers/assets/34794316/0c71035b-789b-4b43-967f-92341276e18f">

### Expected behavior

for container name: 'research-rooms-management staging aws-role'
display entire container name: 'research-rooms-management staging aws-role'
<img width="967" alt="Screenshot 2024-06-17 at 20 03 47" src="https://github.com/mozilla/multi-account-containers/assets/34794316/e26f9414-9d8d-464e-b49c-75fff2cccc1d">
<img width="889" alt="Screenshot 2024-06-17 at 20 14 03" src="https://github.com/mozilla/multi-account-containers/assets/34794316/2edf49c8-9b46-47e1-8381-8d9b61eb015a">

**Comment by dannycolin** [comment]
The container label in the urlbar is managed in Firefox source code itself and not in this addon. This issue should be reported on bugzilla.mozilla.org under Firefox > Address bar. 

For your information, this change in Firefox was made on purpose because long container label were breaking the urlbar UI when the window width was smaller than a certain size. In the meantime, you can hover over the label to see the full container name.

**Comment by itai590** [comment]
Thank You
