### ISSUE TITLE
Missing UI for managing and renaming containers

### ISSUE THREAD

**Issue by dinko** [mozilla/multi-account-containers#2690]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. I click the containers icon next to the search bar.

### Actual behavior

The names of the containers appears, but no UI to change them nor to manage the containers in any other way.

https://github.com/user-attachments/assets/764855d3-19c8-4ef2-bf43-2a30eff7e6c2

### Expected behavior

UI and possibilities to manage the containers appear [as described in the support section](https://support.mozilla.org/en-US/kb/containers#w_manage-your-containers).

### Additional informations

Running on macOS 15.1 (24B83) with Firefox 131.0.2 (aarch64).

**Comment by achernyakevich-sc** [comment]
Looks like you use wrong button. :)

URL bar (you name it as search bar) contains button providing only functionality to make site `Always Open This Site In...`. Button that you need in your browser is not visible because looks as not pinned to toolbar.

Click the button from the screenshot below:
![image](https://github.com/user-attachments/assets/a88776b3-b63e-465b-9a17-9acf2929d324)

Find Multi-Account Containers in the list, click corresponding Gear icon, click `Pin to Toolbar`. After that necessary button will appear in toolbar.

It looks not like a bug. So if solution I provided will work then I would appreciate you close this issue. So other people will be informed that this solution works. :)

**Comment by dinko** [comment]
Perfect, thx…I had the icons mixed up.
