### ISSUE TITLE
Container security "personas"

### ISSUE THREAD

**Issue by brotherdust** [mozilla/multi-account-containers#314]
For instance:
- I often have to deal with devices that have self-signed certificates. How about a way to turn off certificate warnings on a container? Would definitely save me a lot of clicks.
- How about saved credentials that are only available under a specific container?
- How about a setting for containers that don't offer to save passwords or put auto-fill them?

Thanks for your consideration.

**Comment by jonathanKingston** [comment]
I think these are three distinct issues that we should probably solve independently.
The password manager changes are also unlikely to be possible under Test Pilot however we can split this, figure out where it can go and potentially solve this within Firefox code. (I don't actually think we need to give the users the choice for password manager, just implement it).

**Comment by brotherdust** [comment]
Should I close this issue and split each one out as you suggest?

**Comment by kjozwiak** [comment]
> Should I close this issue and split each one out as you suggest?

As Johnathan mentioned above, it's unlikely these features are going to be implemented into the Test Pilot as it would requires some degree of code changes on the platform/firefox side of things. 

We've discussed some of these issues in the past but I would recommend creating three different bugzilla issues and adding them into the container META bug. You can do that by using the following template [here](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody@mozilla.org&blocked=ContextualIdentity&bug_file_loc=http://&bug_ignored=0&bug_severity=normal&bug_status=NEW&cc=tanvi@mozilla.com,kjozwiak@mozilla.com&cf_blocking_b2g=---&cf_blocking_fennec=---&cf_feature_b2g=---&cf_fx_iteration=---&cf_fx_points=---&cf_status_b2g_2_0=---&cf_status_b2g_2_0m=---&cf_status_b2g_2_1=---&cf_status_b2g_2_1_s=---&cf_status_b2g_2_2=---&cf_status_b2g_2_2r=---&cf_status_b2g_2_5=---&cf_status_b2g_2_6=---&cf_status_b2g_master=---&cf_status_firefox47=---&cf_status_firefox48=---&cf_status_firefox49=---&cf_status_firefox50=---&cf_status_firefox_esr38=---&cf_status_firefox_esr45=---&cf_status_thunderbird_esr38=---&cf_status_thunderbird_esr45=---&cf_tracking_b2g=---&cf_tracking_e10s=---&cf_tracking_firefox47=---&cf_tracking_firefox48=---&cf_tracking_firefox49=---&cf_tracking_firefox50=---&cf_tracking_firefox_esr38=---&cf_tracking_firefox_esr45=---&cf_tracking_firefox_relnote=---&cf_tracking_relnote_b2g=---&cf_tracking_thunderbird_esr38=---&cf_tracking_thunderbird_esr45=---&component=DOM:%20Security&contenttypemethod=autodetect&contenttypeselection=text/plain&defined_groups=1&flag_type-203=X&flag_type-37=X&flag_type-4=X&flag_type-41=X&flag_type-5=X&flag_type-607=X&flag_type-720=X&flag_type-721=X&flag_type-737=X&flag_type-781=X&flag_type-787=X&flag_type-799=X&flag_type-800=X&flag_type-803=X&flag_type-835=X&flag_type-846=X&flag_type-855=X&flag_type-863=X&flag_type-864=X&flag_type-875=X&flag_type-889=X&flag_type-892=X&flag_type-901=X&flag_type-905=X&flag_type-908=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Unspecified&priority=--&product=Core&rep_platform=Unspecified&status_whiteboard=[userContextId][domsecurity-backlog]&target_milestone=---&version=unspecified). Once you've created the issues, you can probably close this off :)

This way, once we start triaging issues and feature requests that might go into FX rather than the test pilot experiment, we'll see yours as well :)

**Comment by jonathanKingston** [comment]
These are all out of scope of WebExtensions and I would advise using the link mentioned that Kamil posted.
Issues 2,3 seems like they might be of interest to others I'm not convinced 1. will ever be made a priority personally.
