### ISSUE TITLE
combine addon telemetry data with containers telemetry data

### ISSUE THREAD

**Issue by bakulf** [mozilla/multi-account-containers#321]
I just realized that the use I do of Containers, do not require the use of the addon. Mainly I have 2 containers tabs, both pinned, and session restore to load gmail in those tabs.
From a addon point of view, I don't use containers, but in practice, I am an active user.
Probably we should introduce a ping with containers tabs opened each X minutes. How does it sound?

**Comment by groovecoder** [comment]
FWIW, if you have the add-on installed and you run Firefox, Test Pilot itself will ping that you have it installed and are actively using Firefox with it.

Periodic telemetry pings are problematic for at least a couple reasons:

1. Need to update the privacy notices of the addon
2. Periodic pings make back-end analysis harder - it's harder to measure active usage because we have to filter out the passive periodic pings from the active user-driven pings

Not impossible, but if the main concern is to make sure you're still counted as an "active user" - you should be, even with the usage pattern you describe here.

**Comment by bakulf** [comment]
As discussed on IRC, we want to send a telemetry ping when the tab is activated.
@groovecoder do you want to take this issue?

**Comment by groovecoder** [comment]
I've got https://github.com/mozilla/testpilot-containers/pull/389 for #209. But one of the issues there is that the page count pings are sent on `browser.tabs.onRemoved` events, which do not seem to fire when Firefox quits.

We may be able to build on top of #389 for this, but it will take a bit more planning.

**Comment by groovecoder** [comment]
@bakulf - there's an [`idle` WebExtension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/idle) such that we could start a counter `idle.onStateChanged === "active"` and stop and send the ping `idle.onStateChanged in ["idle", "locked"]`. Would that cover your usage?

**Comment by groovecoder** [comment]
@bakulf and comment here? would the `idle` API/event capture your usage?

**Comment by bakulf** [comment]
Yes, that would work. And maybe we can send a telemetry ping when FF starts if there are containers pinned tabs on startup.

**Comment by dannycolin** [comment]
Closing in favor of [bug 1276002](https://bugzilla.mozilla.org/show_bug.cgi?id=1276002). We definitely to readd some telemetry probes! :)
