### ISSUE TITLE
Open a new tab, then translation in french are missing

### ISSUE THREAD

**Issue by Itazake** [mozilla/multi-account-containers#656]
I'm running firefox 54.0 (64 bits) and I'm a French User.
The problem occurs when I put the mouse hover the (+) icon to open a new tab, and then select a category (for the new tab) like personnal, pro ...
In the new tab there is missing all the translation but we can see all the translation's keys.
Here's a screenshot :
![missingtranslation](https://user-images.githubusercontent.com/29888483/27825368-8c8e56c2-60af-11e7-9f00-eb205cd08946.png)

I've not founded a similar issue in the project's issue list, so I post this one.
If you want some french translation I will be glad to help you :+1:

**Comment by groovecoder** [comment]
Are you also running the Activity Stream Test Pilot experiment?

This looks like [the bug affecting the Activity Stream Test Pilot add-on](https://github.com/mozilla/testpilot-containers/issues/536). It's [supposed to be fixed in the Nightly version of Activity Stream](https://github.com/mozilla/activity-stream/issues/2641#issuecomment-304941646).

**Comment by Itazake** [comment]
Yes i'm also runnning the Activity Stream Test Pilot experiment:
"Containers" and "activity stream"

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
