### ISSUE TITLE
Consider support for 52 ESR

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#686]
We have had a lot of requests for this:
#682, #679, #674, #678, #570, #683 

We could support a version of the addon if there were a decent interest in doing that. At the end of 52 we could migrate to the new Addon we will have.

**Update:** if we wanted to do this, we would have to ship a release to test pilot that then installed and removed the test pilot experiment for these users. This would be it's own addon id and that would be hidden on AMO, at the end of the 52 cycle the same would have to happen (the addon installed in 59 would also have to account for being loaded in 52 as a stud to be updated when the user updates).

**Comment by jonathanKingston** [comment]
For the time being ESR users can do the following:
> Anyway... I would advise ESR users uninstalling the extension through test pilot and using nightly. In about:config change the following after uninstall:
>
> - privacy.userContext.enabled = true
> - privacy.userContext.ui.enabled = true
> - privacy.userContext.longPressBehavior = 2
>
> It is likely this is how they currently are with the extension set up. To modify containers you can go to about:preferences#containers which is navigatable via the Privacy panel.
Basically this is a less feature rich version of what we have here but will keep working for all of the ESR period.

You won't get the same feature set as here however it will allow you to continue working.

**Comment by grahamperrin** [comment]
Context: [RapidRelease/Calendar - MozillaWiki](https://wiki.mozilla.org/RapidRelease/Calendar) with releases 53–58 _not_ gaining extended support.

**Comment by Beurt** [comment]
Unfortunately the fixes mentioned above do not allow ESR users to prevent a specific website to open outside its dedicated container, since we cannot choose a container for a webpage anymore (the button is in the non-functioning menu and not in any other menu).

**Comment by zeromus** [comment]
I couldn't make any sense out of @jonathanKingston 's suggestions (I dont understand the significance of using nightly--am I supposed to use that version, bind it to the profile I want to edit, install the addon there, then change the settings, then run the old ESR 52 again?). I tried this addon in nightly and couldn't find the settings in the location prescribed.

Since I had decided to build my One Last Final Clean Profile before it became hard to get old addons anyway, what I did instead was, from a clean slate, install firefox 51, install the extension, create the container I wanted, create EXTRA containers just in case I would ever need them, then upgrade to 52. If I wanted to do the cleanest job possible, I could have diffed my directories after setting up those containers and tried to apply it to a clean 52. But I think I'll go with this. Now "new container tab" appears and that's all I needed.

Maybe rather than re-engineering all this, someone can just add an extension that crudely edits the containers configuration files through the crudest possible interface.

For what it's worth, I had also tried pasting my old containers.json into my new clean ESR 52 (with the extension installed) but I didn't get the menu items. I guess it needed to do something else to be setup properly.

**Comment by groovecoder** [comment]
At this point, the work required to make the add-on work in 52 ESR is either impossible, or it would take so long that 59 ESR will be available, and the add-on works in 59. 

There also appears to be a work-around for at least some use-cases. So, I'm closing this issue.
