### ISSUE TITLE
disables multi-e10s in FF57

### ISSUE THREAD

**Issue by wanderview** [mozilla/multi-account-containers#865]
When I install this extension I get this pref set automatically:

extensions.e10sMultiBlockedByAddons

Which forces me back to one content process.  This is confusing to me, because I thought that only happened for legacy addons and not web extensions.

Installing other extensions (like ublock origin) does not force this pref on.

**Comment by wanderview** [comment]
Note, the pref is also forced on in FF58 nightly, but I still get 4 content processes for some reason.

**Comment by jonathanKingston** [comment]
zombie said on irc: did you mark it multiprocessCompatible in install.rdf?

**Comment by jonathanKingston** [comment]
Both `extensions.e10sBlockedByAddons` and `extensions.e10sMultiBlockedByAddons` are true for me.

**Comment by jonathanKingston** [comment]
Containers On The Go	1.13	true	{7e56c1ad-71c3-47fe-bdba-372c7770e0cb}
Containers theme	1.0.2	true	{69c84059-c632-41d0-b3bf-ae54aacb632e}
HTTPS Everywhere	2017.9.12.1337	true	https-everywhere-eff-bill@eff.org
Merge Windows	1.0.1	true	{6d0b1446-4a7c-40e9-9bcf-568a8e26d00b}
Multi-Account Containers	4.0.2	true	@testpilot-containers
New container tab	0.2.0	true	{71d4d33f-0bb1-4d92-8389-3f604d62a11a}
Sea Containers	0.8	true	{d975a11d-08cd-4aea-b7c0-989209ad860f}
Snap HTTP Padlocks	1.0.1	true	{95d086c3-8893-451f-8254-d048c0a6ee43}
Wayback Machine	1.8.1	true	wayback_machine@mozilla.org

Other than "Multi-Account Containers" I don't think "Wayback Machine" and "HTTPS Everywhere" are legacy, other than that all the others are web extensions written by myself or a container web extension.

My only other thought is that this is due to other disabled extensions I have and the pref doesn't get updated?

**Comment by shell1** [comment]
so I'll ask Blake how all the prefs interact.   https everywhere has a development version of WE here, https://www.eff.org/files/https-everywhere-test/index.html- but is currently still Legacy.  They were on track to migrate before 57 goes to release.

**Comment by groovecoder** [comment]
Running Containers 4.0.2 on my main Firefox 57.0b3 profile and on a fresh 57.0b3 profile I get:

```
extensions.e10sBlockedByAddons false
extensions.e10sMultiBlockedByAddons true
```
We have [`em:multiprocessCompatible` set to `true` in our `install.rdf`](https://github.com/mozilla/multi-account-containers/blob/production/install.rdf#L8). Is there an additional pref for e10sMulti ?

**Comment by shell1** [comment]
Thank you for reporting this on Beta.  Andym filled a bug filed in bugzilla to fix and it looks like Blakes' patch has been approved.  Now just waiting to uplift to beta https://bugzilla.mozilla.org/show_bug.cgi?id=1404098

**Comment by shell1** [comment]
@groovecoder there isn't anything else that needs to be done to your code.  Making adjustment in the Beta targeting will resolve.

**Comment by groovecoder** [comment]
Thanks. I'll watch the bugzilla bug and close this one when it lands in Beta.

**Comment by wanderview** [comment]
This is working for me in beta 57.

![screenshot 2017-10-03 21 45 16](https://user-images.githubusercontent.com/1256526/31156776-2b76e814-a884-11e7-8fc9-eae579faf426.png)
