### ISSUE TITLE
cookies in 'page info' shows cookies from all the containers

### ISSUE THREAD

**Issue by Ahzaz** [mozilla/multi-account-containers#909]
All cookies from all the containers are shown in 'Page info'. Thus clearing these clears data for all containers.

**Comment by chiraag-nataraj** [comment]
Yes! I saw this as well. Is there any way to attach a Container-specific view of the cookies?

**Comment by Narvey** [comment]
The entire point of this extension (or feature, once merged) is privacy, right? 
Well, the high-privacy workflow would be:

1. Any cookies you need to keep would be in specific containers (e.g. one for Gmail).
2. Everything else would not accept cookies at all, or could be cleared frequently (maybe even more often than on browser close).

And yet it seems this extension does not support the high-privacy workflow. Sad.

I'm a little scared to clear my cookies now (or set the option to clear on exit) because I don't want to ruin the hard cookie-sorting work I already did. Please let me know (with @ sign) as soon as there is a workaround or solution.

**Comment by dobriai** [comment]
Yes, the inability to list/clear the cookies from just the current container is not good news at all! It almost negates the use of containers, IMO. I often want to visit a particular site and then forget it, not keep a devoted Container for just about any site out there!

If I can't at least clear the info associated with a certain Container, then it is back to Private Mode and/or extra Profiles.

I know that there are other, similar requests, and yes, it is not only about cookies - maybe there other settings too, that one might want to manage separately, but Cookies, IMO are a show-stopper!

**Comment by TanviHacks** [comment]
You can clear cookies associated with a specific Container by deleting that Container.  Then you can recreate it (and reassign sites if you had sites assigned to that Container).

You can also use Cookie Auto Delete or another extension that supports Cookies with a Containers view.

This would require mozilla-central platform changes.  The Multi Account Containers addon doesn't have a cookie viewer of it's own.

**Comment by chiraag-nataraj** [comment]
Also, for what it's worth, you can at least see which container a cookie belongs to in `about:preferences#privacy` cookie list.

**Comment by jbyler** [comment]
@chiraag-nataraj, where do you see which container a cookie belongs to?  I'm unable to find that information in the `about:preferences#privacy` cookie list (under "Cookies and Site Data" I clicked "Manage Data..." which opened a dialog titled "Manager Cookies and Site Data" that has a list of cookies.)

**Comment by chiraag-nataraj** [comment]
So...this _used_ to be the case. Then they "revamped" it :rage:. So now you can't even see individual cookies in "Page Info", and they removed the container information in `about:preferences`.
