### ISSUE TITLE
After the extension installation previous custom containers are gone

### ISSUE THREAD

**Issue by deepj** [mozilla/multi-account-containers#915]
It would be great if custom containers aren't gone after the extension installation and keep them instead :)

**Comment by SoftVision-EmilPasca** [comment]
Hi @deepj, thanks for reporting this. However this looks like a duplicate of https://github.com/mozilla/multi-account-containers/issues/894, also this should be fixed in the latest  Beta (57.0b10-20171019140425) and also with the latest Nightly(58.0a1-20171022220103). Please follow along on that thread for more details.
