### ISSUE TITLE
Context Menu of links: Combination of the two „open link in new tab […]“ entries

### ISSUE THREAD

**Issue by fbruetting** [mozilla/multi-account-containers#926]
When you right-click on a link, currently these two options are shown (I translated it, so maybe not the “correct” strings):
- Open link in new tab
- Open link in new tab environment (which contains a sub menu)

Can’t you add the sub menu of the second entry to the first one? Then the context menu get’s shrinked and would be less bloated. The first entry should remain the same as it currently is, so by default open a new tab in the current container.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-619)

**Comment by gliptak** [comment]
https://github.com/mozilla/multi-account-containers/issues/914

**Comment by dannycolin** [comment]
This needs to be reported on bugzilla.mozilla.org since it's a change that needs to be done in Firefox itself. 

Sidenote:
The first element is to open the link in "no container". There's a good chance they decline this feature request because having a clear separation between these two elements is probably more important than the extra space used. 

Closing on our side.
