### ISSUE TITLE
Broken functionality

### ISSUE THREAD

**Issue by physkets** [mozilla/multi-account-containers#927]
I'm currently using Firefox 56.0.2

Clicking on the button does not drop down anything. Just this:

![screenshot_20171029_110257](https://user-images.githubusercontent.com/18267400/32140999-fcbca9f4-bc6b-11e7-8be3-e70a7809ab4e.png)

**Comment by steveregev** [comment]
Same problem with 52.4.0 ESR

**Comment by SoftVision-EmilPasca** [comment]
Hi @physkets, can you please check if `privacy.userContext.enabled` is set to `true` in "about:config"? Also if it is set to `true` can you please add the information from "about:support" page in order to investigate this further? 

@steveregev, we currently do not support Firefox ESR, if you'll like to read more about this issue, please follow along on this thread in https://github.com/mozilla/multi-account-containers/issues/678#issuecomment-315609817.

Thank you.

**Comment by physkets** [comment]
Oh! No, it was set to `false`. I now changed it to `true`, and it works. Thanks! Should I alter any of the other `privacy.userContext.*` settings?

**Comment by grahamperrin** [comment]
Duplicate of [Toolbar button not working · Issue #679 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/679#issuecomment-333444227)
