### ISSUE TITLE
Addon works with Firefox Portable ?

### ISSUE THREAD

**Issue by gomopa** [mozilla/multi-account-containers#932]
Another question please. I installed the addon with my portable Firefox and getting only the deactivated (grey colored) Multi Acoount Container icon.

Does this extension work with FF portable ?

**Comment by groovecoder** [comment]
The add-on is not tested on Firefox Portable. :(

**Comment by gomopa** [comment]
Thanks for your answer groovecoder.
Anyway are you able to say, whether it works or doesn't work with FF portable

**Comment by jonathanKingston** [comment]
As this isn't a Mozilla project I don't think we will be debugging this due to time limitations. I expect the issue might be that portable runs in private mode by default. There are other bugs for this and if they get resolved they will solve this.

I'm going to close this however please report back if you find a solution for this.

Thanks
