### ISSUE TITLE
Icon inconsistencies

### ISSUE THREAD

**Issue by FayneAldan** [mozilla/multi-account-containers#945]
The icons in the popup and in Options (in Firefox 57) are inconsistent in both appearance and order:
![Popup](https://i.imgur.com/XRcUWC4.png)
![Options](https://i.imgur.com/CpeMeI0.png)

Notable inconsistencies:
1. The `circle` icon is positioned at the end in the popup.
2. The positions of the `gift` and `vacation` icons are switched.
3. The `cart` icon is more "solid" in the popup and has more detail in Options.
4. The `dollar` icon is contained within a circle in the popup.
5. The `briefcase` icon is more "solid" in Options and has more detail in the popup.
6. Small detail, but still an inconsistency: In the popup, the `Color` options are shown before the `Icon` options, while Options shows `Icon` first.

**Comment by Paarmita** [comment]
@FayneAldan Can I work on this issue?

**Comment by FayneAldan** [comment]
Make sure you have the extension installed. The first menu is when you click the extension icon and the second menu can be found in Firefox's settings in General.

**Comment by Paarmita** [comment]
@FayneAldan Can u plz help me find the file for the menu window in Firefox's settings. I got the file for popup window.

**Comment by yatri1609** [comment]
@FayneAldan @jonathanKingston @groovecoder Can I work on this issue? And can anyone of you guide me through this?

**Comment by Paarmita** [comment]
@yatri1609 I was working on this. :)

**Comment by jonathanKingston** [comment]
@Paarmita https://searchfox.org/ is a good code searching tool for Firefox.

## Finding the code in Firefox
Sometimes searching for the string like the name in the modal is actually the simplest way to find the code:
["Add new Container" search result](https://searchfox.org/mozilla-central/search?q=Add+new+container&case=false&regexp=false&path=) returns two results, one is the button that opens the modal and another is the modal.
The code being a ftl translation file:
```ftl
containers-window-new =
    .title = Add New Container
```
["containers-window-new" search result](https://searchfox.org/mozilla-central/search?q=containers-window-new&case=false&regexp=false&path=) returns one more result which is the [code that uses the translation](https://searchfox.org/mozilla-central/source/browser/components/preferences/containers.js#20):
```javascript
function setTitle() {
  let params = window.arguments[0] || {};

  let winElem = document.documentElement;
  if (params.userContextId) {
    document.l10n.setAttributes(winElem, "containers-window-update", {
      name: params.identity.name,
    });
  } else {
    document.l10n.setAttributes(winElem, "containers-window-new");
  }
}
```
Looking through this code in the rest of the file you can see it's responsible for opening up the modal and generating these icons.

## The issues
These are all issues within the Firefox codebase and can be changed and tested within a '[artefact build](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Artifact_builds)' and shouldn't require a compile of Firefox.
Follow the instructions to setup your machine:
[Mac](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Mac_OS_X_Prerequisites) [Windows](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites) [Linux](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation)
- After you get the bootstrap.py select artefact build and the script will setup your environment with mercurial and download the code too (you will be prompted at the end, if not follow the rest of the guide).

- Some of the icons being wrong is actually the icons that were in the initial set in Firefox were never updated (the briefcase, cart, dollar)
- The ordering of the modal in the extension came second to the modal within Firefox.
- Likely there will need to be some optimisations to the icons to be placed into the Mozilla codebase.

The work however will need to be moved and logged in http://bugzilla.mozilla.org/ rather than Github. You can mark me as a review when you are done. Please feel to reach out to me with any questions you might have :).

**Comment by Paarmita** [comment]
@jonathanKingston Can u please provide me the link to the communication channel for this project. I tried #containers channel on irc.mozilla.org but couldn't find anyone.

**Comment by jonathanKingston** [comment]
@Paarmita irc is correct for now certainly (sorry I have been a little busy lately) please mention my irc handle (jkt) when messaging. Feel free to email Luke and I directly though instead.

**Comment by iillx** [comment]
Can I work on this one or someone is already doin it? @jonathanKingston @groovecoder

**Comment by groovecoder** [comment]
@iillx I think @Paarmita is already working on this.

**Comment by Paarmita** [comment]
@iillx You can take this up 👍 As I am busy with my university exams So won't be able to work on the issues. :)

**Comment by groovecoder** [comment]
@iillx - are you already working on this? Or can @nidhi-nigam work on it?

**Comment by sakshi97** [comment]
Hi. I would like to work on this issue.

**Comment by kendallcorner** [comment]
@jonathanKingston I have fixed this. I am submitted a bug to bugzilla here https://bugzilla.mozilla.org/show_bug.cgi?id=1570005

I'm working on next steps to get this submitted for review.

![Screenshot from 2019-07-29 14-57-58](https://user-images.githubusercontent.com/3195251/62138693-aa6f0680-b2ad-11e9-9c3c-2106ee171bbc.png)

**Comment by jonathanKingston** [comment]
Thanks @kendallcorner I just approved the change.
