### ISSUE TITLE
How does this damn thing work? There is no real explanation

### ISSUE THREAD

**Issue by michaldybczak** [mozilla/multi-account-containers#969]
I need a Tab Group replacement and this one was suggested. However, I cannot for a life figure out how to add sites to it. I saw the none-helpful "how it works" video and still have no clue.

HOW DO I ADD A SITE TO A GROUP?

The core functionality is not explained. On video suddenly some site is marked as personal or work but where is the group, how I add sites to a group? Usually, I'm able to figure things on my out and despite clean and minimalistic design of the plugin (maybe that's the problem), it's anything but the intuitive.

**Comment by digifu** [comment]
I had the same problem when I tested this add-on as a test-pilot for the first time. Now it's an official add-on, and I still have the same problem. 
My guess is, you can only add a tab to a group in advance. So you click on the icon in your menu-bar (it must be somewhere) and then pick one container and it will open a new tab in that container. But I think it's not possible to drop a tab into a container afterwards. 
As I see it is very useful for different mail- or whatever accounts, because thats what the containers are for - separate the users from each other, but its useless if you want sth to order your already opened tabs.

**Comment by michaldybczak** [comment]
Yeah. In meantime I found this:

https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

So basically Mozilla fails completely to inform what it actually is or isn't. They think about the small stuff like:

     A user may open in account in one container and not understand why they are not logged into the account on other containers.
    A user may browse in their Home container for a bit and not understand why their browsing history shows up in their Work container.

But this is bullshit. The whole idea what the plugin does is incorrectly portrayed. For starters:
- it shows in FF as a replacement for tab groups -> IT ISN'T!!!
- people look for replacement through google and come across this and words "container", "tabs" suggest grouping of tabs somehow, again - THIS IS COMPLETELY DIFFERENT

If they would name it "account containers" or "profile containers" there would be less misunderstanding and confusion. Those "containers" are not for tabs and that's the main problem of communication here. Bad name, bad description, showed in a bad places.

**Comment by dsgn2mfg** [comment]
I agree with the above comments.  It does not group tabs and if you don't have a secondary memory manager there to unload the unused tabs it consumes resources of every tab.  You cannot drag a tab from one container to another.  It just does not help with organizing.  Maybe this is because the instructions suck but I don't think so; I think it is because the people that wrote it and said it would replace "Tab Groups" never tried to use it for grouping tabs to tasks or functions.  Additionally as you put tabs into the container all tabs in all containers show up.  I only want to be able to see one container at a time and only the tabs that art in that container except those that are pinned to the tab bar which should always be there and visible.  Ideally only tabs in the active container should be using computer resources and those in inactive containers don't use resources until that container is activated.  Only one container at a time should be active except if you are dragging and dropping tabs from one container to another; it that situation you may need to have two containers using resources but once the d&d is complete only the active container's tabs should be visible.

**Comment by falolaf** [comment]
Could any of these work as a replacement for Tab Groups:
https://addons.mozilla.org/sv-SE/firefox/addon/sync-tab-groups/
https://addons.mozilla.org/en-US/firefox/addon/tabmarks/

Then this one aims to be a Tab Groups replacecment:
https://addons.mozilla.org/en-US/firefox/addon/conex/
(When the referenced bug is fixed.)

**Comment by groovecoder** [comment]
This add-on implements some similar functionality to Tab Groups, but isn't designed to be a comprehensive replacement.
